/*
================================================================================
PROJECT:       [RADIOISOTOPO]
VERSION:       1.0.0
DESCRIPTION:   [Archivo de traducciones]
AUTHOR:        [Marcos, Wael]
UPDATED:       [23/04/2026]
================================================================================
*/

export const textos = {
    Castellano: {
        // LOGIN
        bienvenidoAreaPrivada: "Bienvenido/a a la Área Privada",
        accederCuentaGestion: "Accede a tu cuenta de gestión",
        correoElectronico: "Correo electrónico...",
        contrasena: "Contraseña...",
        recordarme: "Recordarme",
        quieresCambiarContrasena: "¿Quieres cambiar tu contraseña?",
        iniciarSesion: "Iniciar sesión",
        
        // SIDEBAR
        radioisotopos: "Radioisótopos",
        paginaPrincipal: "Página Principal",
        pacientes: "Pacientes",
        gestionUsuarios: "Gestión Usuarios",
        auditoria: "Auditoría",
        configuracion: "Configuración",
        cerrarSesion: "Cerrar Sesión",
        seguroCerrarSesion: "¿Seguro que quieres cerrar sesión?",
        cancelar: "Cancelar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínico",
        conexionCifrada: "Conexión cifrada de extremo a extremo",
        avisosDelSistema: "Avisos del Sistema",
        nuevos: "nuevos",
        noHayNotificaciones: "No hay notificaciones pendientes",
        dr: "Dr.",
        especialista: "Especialista",
        perfilDelUsuario : "Perfil de Usuario",
        
        // HOMEPAGE
        inicio: "Inicio",
        resumenDispositivosPacientes: "Resumen del estado de los dispositivos y pacientes en tratamiento",
        pacientesActivos: "Pacientes Activos",
        alertasDeHoy: "Alertas de hoy",
        sincronizacion: "Sincronización",
        pacientesRevisadosRecientemente: "Pacientes revisados recientemente",
        noHasRevisadoPacientes: "No has revisado pacientes recientemente.",
        ahoraMismo: "Ahora mismo",
        haceMin: "Hace {min}min",
        haceH: "Hace {horas}h",
        
        // PACIENTE PAGE
        gestionDePacientes: "Gestión de pacientes",
        gestionDispositivosTratamientos: "Gestión de dispositivos y supervisión de tratamientos",
        anadirPaciente: "Añadir Paciente",
        buscarPorTarjetaSanitaria: "Buscar por tarjeta sanitaria del paciente o nombre...",
        estadoTodos: "Estado (Todos)",
        establePositivo: "Estable / Positivo",
        ansiedadDepresion: "Ansiedad / Depresión",
        tratamientoTodos: "Tratamiento (Todos)",
        iodo: "Iodo",
        cobalto: "Cobalto",
        paciente: "PACIENTE",
        estado: "ESTADO",
        tratamiento: "TRATAMIENTO",
        progreso: "PROGRESO",
        acciones: "ACCIONES",
        cargandoDatosClinicos: "Cargando datos clínicos reales...",
        verPerfil: "Ver Perfil",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "Alta de nuevo paciente y tratamiento",
        registroSalutCatalunya: "Registro al fitxer de Salut de Catalunya (CatSalut)",
        datosPersonales: "Datos Personales (CatSalut)",
        nomCognoms: "Nombre y Apellidos",
        ejemploNombre: "Ej: Marcos Góngora",
        cipTargetaSanitaria: "CIP (Tarjeta Sanitaria)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Fecha de nacimiento",
        hospitalReferencia: "Hospital de Referencia",
        tractamentRadioisotops: "Tratamiento de Radioisótopos",
        tipusRadioisotop: "Tipo de Radioisótopo",
        seleccionaIsotopo: "Selecciona un isótopo...",
        iodo131: "Iodo-131",
        lutecio177: "Lutecio-177",
        cobalto60: "Cobalto-60",
        dosiAdministrada: "Dosis Administrada",
        ejemploDosis: "Ej: 370",
        unitats: "Unidades",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Milicurio (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Fecha y hora de administración",
        sincronitzacioDispositius: "Sincronización de Dispositivos",
        apropaSmartWatch: "Acerca el SmartWatch compatible del paciente para iniciar la vinculación.",
        buscarDispositiuNFC: "Buscar dispositivo NFC",
        resumAlta: "Resumen del Alta",
        consentimentInformat: "Consentimiento informado registrado.",
        monitoritzacioZeroConfig: "Monitorización Zero-Config activa.",
        calculDecayefectiu: "Cálculo de decaimiento según Te efectivo.",
        confirmarIniciar: "Confirmar e Iniciar",
        porFavorCompletaCampos: "Por favor, completa todos los campos técnicos.",
        sincronizandoCatsalut: "Sincronizando con CatSalut y generando informe...",
        altaCompletada: "Alta completada e informe descargado con éxito.",
        errorProcesoAlta: "Error en el proceso de alta",
        aprobaSmartWatch: "Acerca el SmartWatch compatible del paciente para iniciar la vinculación.",
        buscandoDispositivo: "Buscando dispositivo...",
        relojVinculado: "Reloj vinculado",
        errorVinculacionBluetooth: "Error al vincular Bluetooth",
        buscando: "Buscando...",
        cambiarReloj: "Cambiar Reloj",
        vincularBluetooth: "Vincular Bluetooth",
         
        // PERFIL PACIENTE
        patientNoSeleccionado: "Paciente no seleccionado",
        sinTratamiento: "Sin tratamiento",
        noVinculado: "No vinculado",
        noVinculadoStatus: "No vinculado",
        conectadoTransmitiendo: "Conectado y transmitiendo",
        tractamentActiu: "Tratamiento Activo",
        idPaciente: "ID Paciente",
        dispositivoSmartwatch: "Dispositivo Smartwatch",
        bateria: "Batería",
        ultimaSinc: "Última sinc",
        sincronizacionRemota: "Sincronización Remota",
        desconectar: "Desconectar",
        descargaBiometriaAutomatica: "La descarga de biometría es automática desde el dispositivo del paciente.",
        progresoRadioterapia: "Progreso Radioterapia",
        cargaActiva: "Carga Activa",
        consonanciaSalud: "Consonancia de Salud",
        empujarConsejosReloj: "Envía consejos personalizados a la pantalla del reloj",
        hidratacionBeberAgua: "Hidratar: Beber 2L de agua hoy",
        enviadoALas: "Enviado a las",
        seleccionarConsejo: "Seleccionar consejo predefinido...",
        evitarContactoNinos: "Evitar contacto con niños (24h)",
        beberLiquido: "Beber abundante líquido",
        usarBanoExclusivo: "Usar baño exclusivo",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolución semanal)",
        esteEsEstadoDiario: "Estado diario del paciente (defecto 50%).",
        centroComunicacion: "Centro de comunicación directa",
        consultaGeneral: "Consulta General",
        mensajeMedico: "Mensaje del Médico",
        noHayMensajesNuevos: "No se han recibido mensajes nuevos hoy.",
        mensajeEnviadoExito: "Consejo enviado al Smartwatch con éxito",
        errorEnviarConsejo: "Error al enviar el consejo",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "Alta de Nuevo Personal Médico",
        completaDatosRegistrar: "Completa los datos para registrar un nuevo especialista.",
        datosAcceso: "Datos de Acceso (Usuario)",
        nombreCompleto: "Nombre Completo",
        ejemploNombreCompleto: "Ej. Carlos Ruiz",
        correoCorporativo: "Correo Electrónico Corporativo",
        ejemploCorreo: "carlos.ruiz@hospital.com",
        contrasenaTemporal: "Contraseña Temporal",
        asignaContrasena: "Asigna una contraseña",
        hospitalReferenciaInput: "Hospital de Referencia",
        ejemploHospital: "Ej. Hospital Clínic",
        datosProfesionales: "Datos Profesionales (Médico)",
        especialidad: "Especialidad",
        seleccionaEspecialidad: "Selecciona una especialidad...",
        oncologiaRadioterapica: "Oncología Radioterápica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiología",
        fisicaMedica: "Física Médica",
        numeroColegiado: "Número de Colegiado",
        ejemploColegiado: "Ej. 282893939",
        conectandoServidor: "Conectando con el servidor de Render...",
        medicoRegistrado: "Médico registrado correctamente.",
        errorComunicarServidor: "Error al comunicar con el servidor.",
        procesar: "Procesando...",
        registrarMedicoSistema: "Registrar Médico en el Sistema",
        
        // CONFIGURACION
        configuracionSistema: "Configuración del Sistema",
        ajustesCuentaAlertas: "Ajustes de cuenta, alertas y preferencias",
        datosCuenta: "Datos de la Cuenta",
        nombreProfesional: "Nombre del Profesional",
        correoElectronicoInput: "Correo Electrónico",
        especialidadInput: "Especialidad",
        administracionSistemas: "Administración de Sistemas",
        cambiarContrasena: "Cambiar contraseña",
        preferenciasSistema: "Preferencias del Sistema",
        idiomaInterfaz: "Idioma de la interfaz",
        zonaHoraria: "Zona Horaria",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionesClinicas: "Notificaciones Clínicas",
        bateriaBajaDispositivos: "Batería baja en dispositivos",
        avisarSmartWatchBaja: "Avisar si baja del 15%",
        desconexionBiometrica: "Desconexión biométrica",
        alertaPerdidaSenal: "Alerta inmediata si se pierde señal",
        resumenSemanal: "Resumen semanal",
        recibirInformeCorreo: "Recibir informe por correo",
        alertaRadiacionSegura: "Alerta de Radiación Segura",
        avisarPacienteNiveles: "Avisar en niveles seguros",
        anomaliaConstantesVitales: "Anomalía en Constantes Vitales",
        notificarAlteraciones: "Notificar alteraciones cardíacas",
        falloSincronizacion: "Fallo de sincronización",
        avisarRelojNoEnvia: "Avisar si no envía datos (12h)",
        zonaSeguridad: "Zona de Seguridad",
        gestionarSesionesPermisos: "Gestiona sesiones y permisos.",
        cerrarSesionTodosTerminales: "Cerrar sesión en todos los terminales",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Seguridad de la Cuenta",
        introduceContrasenaActual: "Introduce tu contraseña actual y la nueva.",
        contrasenaActual: "Contraseña actual",
        nuevaContrasena: "Nueva contraseña",
        confirmarNuevaContrasena: "Confirmar nueva contraseña",
        contrasenasNoCoinciden: "Las contraseñas nuevas no coinciden",
        contrasenaMinimoCaracteres: "Mínimo 6 caracteres",
        contrasenaActualizadaExito: "¡Contraseña actualizada!",
        volverAtras: "Volver atrás",
        actualizarContrasena: "Actualizar Contraseña",
        
        // AUDITORIA
        panelAuditoria: "Panel de Auditoría",
        controlAccesoSeguridad: "Control de acceso y seguridad",
        facultativo: "FACULTATIVO",
        especialidadHeader: "ESPECIALIDAD",
        hospital: "HOSPITAL",
        estadoHeader: "ESTADO",
        accionesSeguridad: "ACCIONES SEGURIDAD",
        accediendoRegistros: "Accediendo a registros...",
        noHayFacultativos: "No hay facultativos.",
        seguroCambiarEstado: "¿Cambiar estado a {nuevoEstado}?",
        exitoContrasenaActualizada: "Éxito: Contraseña de {nombre} actualizada.",
        errorCambiarEstado: "Error al cambiar el estado.",
        asignarNuevaContrasena: "Nueva contraseña para {nombre}:",
        suspend: "Suspender",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviando: "Enviando...",
        
        // ESTADOS
        estable: "Estable",
        activo: "ACTIVO",
        inactivo: "INACTIVO",

        // LANDING PAGE
        tecnologiaNuclear: "Tecnología Nuclear Avanzada",
        gestioInteligent: "Gestión Inteligente de ",
        radiofarmacsClinics: "Radiofármacos Clínicos",
        plataformaIntegral: "Plataforma integral para hospitales y centros de medicina nuclear. Monitorización en tiempo real, trazabilidad completa y protocolos de seguridad certificados.",
        demanaInformacio: "Solicitar Información",
        veureDemo: "Ver Demo",
        caracteristiques: "Características",
        estatArtControl: "El estado del arte en control hospitalario",
        solucioCompleta: "Una solución completa diseñada para profesionales de la medicina nuclear, con las herramientas más avanzadas del mercado.",
        monitoritzacioPacients: "Monitorización de Pacientes",
        seguimentLogic: "Seguimiento preciso de dosis e historial de administración en tiempo real. Gráficas interactivas y alertas personalizadas.",
        alertesSeguretat: "Alertas de Seguridad",
        protocolAutematic: "Protocolo automático y notificaciones de emergencia para personal facultativo. Integración con sistemas hospitalarios.",
        informesAuditoria: "Informes de Auditoría",
        generacioAutomatitzada: "Generación automatizada de trazabilidad para cumplimiento normativo. Exportación en múltiples formatos certificados.",
        analyticsAvancat: "Analytics Avanzado",
        dashboardInteligent: "Dashboard inteligente con métricas clave, tendencias históricas y predicciones basadas en IA.",
        complimentNormatiu: "Cumplimiento Normativo",
        normativaEuropea: "Cumplimiento total de la normativa europea e internacional. Certificaciones ISO 9001 e ISO 27001.",
        xifratGrauMedic: "Cifrado de Grado Médico",
        protectioDades: "Protección de datos de pacientes con cifrado AES-256. Backup automático y recuperación de desastres.",
        mesInformacio: "Más información",
        solucionsIntegrals: "Soluciones Integrales",
        dissenyatEquips: "Diseñado para equipos médicos de excelencia",
        plataformaIntegra: "Nuestra plataforma se integra perfectamente con sus sistemas existentes, proporcionando una experiencia fluida y eficiente para todo el equipo.",
        integracioApi: "Multi Centro",
        connecteuSistemes: "Gestione múltiples centros desde una única plataforma con control centralizado.",
        suport247: "Soporte 24/7",
        equipEspecialistes: "Equipo de especialistas disponible las 24 horas para ayudarle.",
        formacioInclosa: "Formación Incluida",
        cursosCertificacio: "Cursos de certificación para todo el equipo médico incluidos.",
        prepareuHospital: "Prepare su hospital para el futuro",
        contacteuNosaltres: "Póngase en contacto con nosotros para obtener más información sobre cómo Radioisótopos puede mejorar la gestión de su centro.",
        contactaNos: "Contáctenos",
        respostaMenys24h: "Respuesta en menos de 24h",
        assessoriaPersonalitzada: "Asesoría personalizada",
        senseCompromis: "Sin compromiso",
        demo: "Demo",
        quePodeuMonitoritzar: "Qué puedes monitorizar",
        descobrirFuncionalitats: "Descubre las diferentes funcionalidades del sistema de gestión de radiofármacos.",
        panellPacients: "Panel de Pacientes",
        visualitzaRealTime: "Visualiza en tiempo real el estado de cada paciente y las dosis administradas.",
        estadistiquesDetallades: "Estadísticas Detalladas",
       grafiquesInformes: "Gráficas e informes con las métricas más importantes de tu centro.",
        sistemaAuditoria: "Sistema de Auditoría",
        registreComplet: "Registro completo de todas las acciones para cumplir la normativa vigente.",
        sistemaAlertes: "Sistema de Alertas",
        notificacionsAutomaticas: "Notificaciones automáticas para dosis críticas y emergencias.",
        creacioPacient: "Creación de Paciente",
        calculAutoma: "Selecciona isótopo y dosis - el sistema calcula automáticamente la actividad necesaria",
        generacioInformes: "Generación de Informes",
        creaExportaInformes: "Crea y exporta informes personalizados para cada departamento.",
        seguretatTotal: "Seguridad Total",
        protocolsCertificats: "Protocolos certificados",
        precisio: "+98% Precisión",
        dadesRealTime: "Datos en tiempo real",
        hospitalsConnectats: "Hospitales Conectados",
        pacientsMonitoritzats: "Pacientes Monitorizados",
        disponibilitat: "Disponibilidad",
        incidentsSeguretat: "Incidentes de Seguridad",
        producte: "Producto",
        preus: "Precios",
        integracions: "Centros",
        actualitzacions: "Actualizaciones",
        empresa: "Empresa",
        sobreNosaltres: "Sobre Nosotros",
        carreres: "Carreras",
        premsa: "Prensa",
        contacte: "Contacto",
        recursos: "Recursos",
        documentacio: "Documentación",
        api: "API",
        suport: "Soporte",
        estatSistema: "Estado del Sistema",
        politicaPrivacitat: "Política de Privacidad",
        privacidadTitulo: "Privacidad y Términos",
        termesServei: "Términos de Servicio",
        cookies: "Cookies",
        totsDretsReservats: "Todos los derechos reservados.",
        cookiesTitol: "🍪 Cookies",
        cookiesMensaje: "Usamos cookies propias para mejorar tu experiencia y mantener tu sesión iniciada.",
        cookiesTipos: "essentiales: sesión (1 año), seguridad. No usamos cookies de análisis o publicidad.",
        cookiesAceptar: "Aceptar",
        cookiesMasInfo: "Política de privacidad",
        privacidadActualizada: "Última actualización: Abril 2026",
        privacidadResponsable: "Responsable del tratamiento",
        privacidadDatos: "Los datos que recopilamos son tratados por:",
        privacidadRecopilacion: "Datos que recopilamos",
        privacidadRecopilacionTexto: "Recopilamos los siguientes datos:",
        privacidadDatosCuenta: "Datos de tu cuenta (nombre, email, rol)",
        privacidadDatosPaciente: "Datos de pacientes (nombre, historial médico)",  
        privacidadDatosLogs: "Logs de acceso y acciones",
        privacidadUso: "Finalidad del tratamiento",
        privacidadUsoTexto: "Usamos tus datos para:",
        privacidadProporcionar: "Proporcionar el servicio de gestión de radiofármacos",
        privacidadCumplir: "Cumplir con obligaciones legales (normativa sanitaria)",
        privacidadMejorar: "Mejorar el servicio",
        privacidadCookies: "Cookies",
        privacidadCookiesTexto: "Este sitio usa cookies propias:",
        privacidadSesion: "Cookie de sesión (1 año)",
        privacidadSesion_desc: "Mantiene tu sesión iniciada. Se renueva automáticamente.",
        privacidadSeguridad: "Cookie de seguridad",
        privacidadSeguridad_desc: "Protege contra ataques CSRF",
        privacidadNoAnaliticos: "No usamos cookies de análisis ni publicidad",
        privacidadDerechos: "Tus derechos",
        privacidadDerechosTexto: "Tienes derecho a:",
        privacidadAcceso: "Acceder a tus datos",
        privacidadRectificacion: "Rectificar datos incorrectos",
        privacidadSupresion: "Solicitar supresión",
        privacidadPortabilidad: "Recibir tus datos en formato portable",
        privacidadContacto: "Contacto",
        privacidadContactoTexto: "Para ejercer tus derechos o cualquier consulta:",
        volverInicio: "Volver al inicio",
        terminosTexto: "Al acceder y usar este sitio, aceptas las siguientes condiciones:",
        terminosAceptacion: "Aceptación",
        terminosAceptacionTxt: "Al usar este servicio aceptas cumplir estos términos.",
        terminosUso: "Uso del servicio",
        terminosUsoTxt: "El servicio es para gestión de radiofármacos en centros sanitarios.",
        terminosLimitacion: "Limitación de responsabilidad",
        terminosLimitacionTxt: "No nos hacemos responsables del uso indebido del software.",
        terminosCambios: "Cambios",
        terminosCambiosTxt: "Podemos modificar estos términos sin previo aviso.",
    },

    Catala: {
        // LOGIN
        bienvenidoAreaPrivada: "Benvingut/da a l'Àrea Privada",
        accederCuentaGestion: "Accedeix al teu compte de gestió",
        correoElectronico: "Correu electrònic...",
        contrasena: "Contrasenya...",
        recordarme: "Recorda'm",
        quieresCambiarContrasena: "Vols canviar la contrasenya?",
        iniciarSesion: "Iniciar sessió",
        
        // SIDEBAR
        radioisotopos: "Radioisòtops",
        paginaPrincipal: "Pàgina Principal",
        pacientes: "Pacients",
        gestionUsuarios: "Gestió Usuaris",
        auditoria: "Auditoria",
        configuracion: "Configuració",
        cerrarSesion: "Tancar Sessió",
        seguroCerrarSesion: "Segur que vols tancar sessió?",
        cancelar: "Cancel·lar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínic",
        conexionCifrada: "Connexió xifrada d'extrem a extrem",
        avisosDelSistema: "Avisos del Sistema",
        nuevos: "nous",
        noHayNotificaciones: "No hi ha notificacions pendents",
        dr: "Dr.",
        especialista: "Especialista",
        perfilDelUsuario: "Perfil d'Usuari",
        
        // HOMEPAGE
        inicio: "Inici",
        resumenDispositivosPacientes: "Resum de l'estat dels dispositius i pacients en tractament",
        pacientesActivos: "Pacients Actius",
        alertasDeHoy: "Alertes d'avui",
        sincronizacion: "Sincronització",
        pacientesRevisadosRecientemente: "Pacients revisats recentment",
        noHasRevisadoPacientes: "No has revisat pacients recentment.",
        ahoraMismo: "Ara mateix",
        haceMin: "Fa {min}min",
        haceH: "Fa {horas}h",
        
        // PACIENTE PAGE
        gestionDePacientes: "Gestió de pacients",
        gestionDispositivosTratamientos: "Gestió de dispositius i supervisió de tractaments",
        anadirPaciente: "Afegir Pacient",
        buscarPorTarjetaSanitaria: "Cercar per targeta sanitària o nom...",
        estadoTodos: "Estat (Tots)",
        establePositivo: "Estable / Positiu",
        ansiedadDepresion: "Ansietat / Depressió",
        tratamientoTodos: "Tractament (Tots)",
        iodo: "Iode",
        cobalto: "Cobalt",
        paciente: "PACIENT",
        estado: "ESTAT",
        tratamiento: "TRACTAMENT",
        progreso: "PROGRÉS",
        acciones: "ACCIONS",
        cargandoDatosClinicos: "Carregant dades clíniques reals...",
        verPerfil: "Veure Perfil",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "Alta de nou pacient i tractament",
        registroSalutCatalunya: "Registre al fitxer de Salut de Catalunya (CatSalut)",
        datosPersonales: "Dades Personals (CatSalut)",
        nomCognoms: "Nom i Cognoms",
        ejemploNombre: "Ex: Marc García",
        cipTargetaSanitaria: "CIP (Targeta Sanitària)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Data de naixement",
        hospitalReferencia: "Hospital de Referència",
        tractamentRadioisotops: "Tractament de Radioisòtops",
        tipusRadioisotop: "Tipus de Radioisòtop",
        seleccionaIsotopo: "Selecciona un isòtop...",
        iodo131: "Iode-131",
        lutecio177: "Luteci-177",
        cobalto60: "Cobalt-60",
        dosiAdministrada: "Dosi Administrada",
        ejemploDosis: "Ex: 370",
        unitats: "Unitats",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Milicuri (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Data i hora d'administració",
        sincronitzacioDispositius: "Sincronització de Dispositius",
        apropaSmartWatch: "Apropa el SmartWatch compatible del pacient per iniciar la vinculació.",
        buscarDispositiuNFC: "Cercar dispositiu NFC",
        resumAlta: "Resum de l'Alta",
        consentimentInformat: "Consentiment informat registrat.",
        monitoritzacioZeroConfig: "Monitorització Zero-Config activa.",
        calculDecayefectiu: "Càlcul de decaïment segons Te efectiu.",
        confirmarIniciar: "Confirmar i Iniciar",
        porFavorCompletaCampos: "Si us plau, completa tots els camps tècnics.",
        sincronizandoCatsalut: "Sincronitzant amb CatSalut i generant informe...",
        altaCompletada: "Alta completada i informe descarregat amb èxit.",
        errorProcesoAlta: "Error en el procés d'alta",
        aprobaSmartWatch: "Apropa el SmartWatch compatible del pacient per iniciar la vinculació.",
        buscandoDispositivo: "Cercant dispositiu...",
        relojVinculat: "Rellotge vinculat",
        errorVinculacioBluetooth: "Error al vincular Bluetooth",
        buscando: "Cercant...",
        cambiarRellotge: "Canviar Rellotge",
        vincularBluetooth: "Vincular Bluetooth",
         
        // PERFIL PACIENTE
        patientNoSeleccionado: "Pacient no seleccionat",
        sinTratamiento: "Sense tractament",
        noVinculado: "No vinculat",
        noVinculadoStatus: "No vinculat",
        conectadoTransmitiendo: "Connectat i transmetent",
        tractamentActiu: "Tractament Actiu",
        idPaciente: "ID Pacient",
        dispositivoSmartwatch: "Dispositiu Smartwatch",
        bateria: "Bateria",
        ultimaSinc: "Última sinc",
        sincronizacionRemota: "Sincronització Remota",
        desconectar: "Desconnectar",
        descargaBiometriaAutomatica: "La descàrrega de biometria és automàtica des del dispositiu.",
        progresoRadioterapia: "Progrés Radioteràpia",
        cargaActiva: "Càrrega Activa",
        consonanciaSalud: "Concordança de Salut",
        empujarConsejosReloj: "Envia consells personalitzats a la pantalla del rellotge",
        hidratacionBeberAgua: "Hidratació: Beure 2L d'aigua avui",
        enviadoALas: "Enviat a les",
        seleccionarConsejo: "Seleccionar consell predefinit...",
        evitarContactoNinos: "Evitar contacte amb nens (24h)",
        beberLiquido: "Beure líquid abundant",
        usarBanoExclusivo: "Usar lavabo exclusiu",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolució setmanal)",
        esteEsEstadoDiario: "Estat diari del pacient (defecte 50%).",
        centroComunicacion: "Centre de comunicació directa",
        consultaGeneral: "Consulta General",
        mensajeMedico: "Missatge del Metge",
        noHayMensajesNuevos: "No s'han rebut missatges nous avui.",
        mensajeEnviadoExito: "Consell enviat al Smartwatch amb èxit",
        errorEnviarConsejo: "Error en enviar el consell",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "Alta de Nou Personal Mèdic",
        completaDatosRegistrar: "Completa les dades per registrar un nou especialista.",
        datosAcceso: "Dades d'Accés (Usuari)",
        nombreCompleto: "Nom Complet",
        ejemploNombreCompleto: "Ex. Carles Ruiz",
        correoCorporativo: "Correu Electrònic Corporatiu",
        ejemploCorreo: "carles.ruiz@hospital.com",
        contrasenaTemporal: "Contrasenya Temporal",
        asignaContrasena: "Assigna una contrasenya",
        hospitalReferenciaInput: "Hospital de Referència",
        ejemploHospital: "Ex. Hospital Clínic",
        datosProfessionals: "Dades Professionals (Metge)",
        especialidad: "Especialitat",
        seleccionaEspecialidad: "Selecciona una especialitat...",
        oncologiaRadioterapica: "Oncologia Radioteràpica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiologia",
        fisicaMedica: "Física Mèdica",
        numeroColegiado: "Número de Col·legiat",
        ejemploColegiado: "Ex. 282893939",
        conectandoServidor: "Connectant amb el servidor de Render...",
        medicoRegistrado: "Metge registrat correctament.",
        errorComunicarServidor: "Error en comunicar amb el servidor.",
        procesar: "Processant...",
        registrarMedicoSistema: "Registrar Metge al Sistema",
        
        // CONFIGURACION
        configuracionSistema: "Configuració del Sistema",
        ajustesCuentaAlertas: "Ajustos de compte, alertes i preferències",
        datosCuenta: "Dades del Compte",
        nombreProfesional: "Nom del Professional",
        correoElectronicoInput: "Correu Electrònic",
        especialidadInput: "Especialitat",
        administracionSistemas: "Administració de Sistemes",
        cambiarContrasena: "Canviar contrasenya",
        preferenciasSistema: "Preferències del Sistema",
        idiomaInterfaz: "Idioma de la interfície",
        zonaHoraria: "Zona Horària",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionesClinicas: "Notificacions Clíniques",
        bateriaBajaDispositivos: "Bateria baixa en dispositius",
        avisarSmartWatchBaja: "Avisar si baixa del 15%",
        desconexionBiometrica: "Desconnexió biomètrica",
        alertaPerdidaSenal: "Alerta immediata si es perd el senyal",
        resumenSemanal: "Resum setmanal",
        recibirInformeCorreo: "Rebre informe per correu",
        alertaRadiacionSegura: "Alerta de Radiació Segura",
        avisarPacienteNiveles: "Avisar en nivells segurs",
        anomaliaConstantesVitales: "Anomalia en Constants Vitals",
        notificarAlteraciones: "Notificar alteracions cardíaques",
        falloSincronizacion: "Fallada de sincronització",
        avisarRelojNoEnvia: "Avisar si no envia dades (12h)",
        zonaSeguridad: "Zona de Seguretat",
        gestionarSesionesPermisos: "Gestiona sessions i permisos.",
        cerrarSesionTodosTerminales: "Tancar sessió a tots els terminals",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Seguretat del Compte",
        introduceContrasenaActual: "Introdueix la contrasenya actual i la nova.",
        contrasenaActual: "Contrasenya actual",
        nuevaContrasena: "Nova contrasenya",
        confirmarNuevaContrasena: "Confirmar nova contrasenya",
        contrasenasNoCoinciden: "Les contrasenyes noves no coincideixen",
        contrasenaMinimoCaracteres: "Mínim 6 caràcters",
        contrasenaActualizadaExito: "¡Contrasenya actualitzada amb èxit!",
        volverAtras: "Tornar enrere",
        actualizarContrasena: "Actualitzar Contrasenya",
        
        // AUDITORIA
        panelAuditoria: "Panell d'Auditoria",
        controlAccesoSeguridad: "Control d'accés i seguretat",
        facultativo: "FACULTATIU",
        especialidadHeader: "ESPECIALITAT",
        hospital: "HOSPITAL",
        estadoHeader: "ESTAT",
        accionesSeguridad: "ACCIONS SEGURETAT",
        accediendoRegistros: "Accedint a registres...",
        noHayFacultativos: "No hi ha facultatius.",
        seguroCambiarEstado: "¿Canviar estat a {nuevoEstado}?",
        exitoContrasenaActualizada: "Èxit: Contrasenya de {nombre} actualitzada.",
        errorCambiarEstado: "Error en canviar l'estat.",
        asignarNuevaContrasena: "Nova contrasenya per a {nombre}:",
        suspend: "Suspendre",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviando: "Enviant...",
        
        // ESTADOS
        estable: "Estable",
        activo: "ACTIU",
        inactivo: "INACTIU",

        // LANDING PAGE
        tecnologiaNuclear: "Tecnologia Nuclear Avançada",
        gestioInteligent: "Gestió Intel·ligent de ",
        radiofarmacsClinics: "Radiofàrmacs Clínics",
        plataformaIntegral: "Plataforma integral per a hospitals i centres de medicina nuclear. Monitorització en temps real, traçabilitat completa i protocols de seguretat certificats.",
        demanaInformacio: "Demanar Informació",
        veureDemo: "Veure Demo",
        caracteristiques: "Característiques",
        estatArtControl: "L'estat de l'art en control hospitalari",
        solucioCompleta: "Una solució completa dissenyada per a professionals de la medicina nuclear, amb les eines més avançades del mercat.",
        monitoritzacioPacients: "Monitorització de Pacients",
        seguimentLogic: "Seguiment precís de dosis i historial d'administració en temps real. Gràfiques interactives i alertes personalitzades.",
        alertesSeguretat: "Alertes de Seguretat",
        protocolAutematic: "Protocol automàtic i notificacions d'emergència per a personal facultatiu. Integració amb sistemes hospitalaris.",
        informesAuditoria: "Informes d'Auditoria",
        generacioAutomatitzada: "Generació automatitzada de traçabilitat per a compliment normatiu. Exportació en múltiples formats certificats.",
        analyticsAvancat: "Analytics Avançat",
        dashboardInteligent: "Dashboard intel·ligent amb mètriques clau, tendències històriques i prediccions basades en IA.",
        complimentNormatiu: "Compliment Normatiu",
        normativaEuropea: "Compliment total de la normativa europea i internacional. Certificacions ISO 9001 i ISO 27001.",
        xifratGrauMedic: "Xifrat de Grau Mèdic",
        protectioDades: "Protecció de dades de pacients amb xifrat AES-256. Backup automàtic i recuperació de desastres.",
        mesInformacio: "Més informació",
        solucionsIntegrals: "Solucions Integrals",
        dissenyatEquips: "Dissenyat per a equips mèdics d'excel·lència",
        plataformaIntegra: "La nostra plataforma s'integra perfectament amb els vostres sistemes existents, proporcionant una experiència fluida i eficient per a tot l'equip.",
        integracioApi: "Multi Centre",
        connecteuSistemes: "Gestioni múltiples centres des d'una única plataforma amb control centralitzat.",
        suport247: "Suport 24/7",
        equipEspecialistes: "Equip d'especialistes disponible les 24 hores per ajudar-vos.",
        formacioInclosa: "Formació Inclòsa",
        cursosCertificacio: "Cursos de certificació per a tot l'equip mèdic inclosos.",
        prepareuHospital: "Prepareu el vostre hospital pel futur",
        contacteuNosaltres: "Posa't en contacte amb nosaltres per obtenir més informació sobre com Radioisòtops pot millorar la gestió del teu centre.",
        contactaNos: "Contacta'ns",
        respostaMenys24h: "Resposta en menys de 24h",
        assessoriaPersonalitzada: "Assessoria personalitzada",
        senseCompromis: "Sense compromís",
        demo: "Demo",
        quePodeuMonitoritzar: "Què pots monitoritzar",
        descobrirFuncionalitats: "Descobreix les diferents funcionalitats del sistema de gestió de radiofàrmacs.",
        panellPacients: "Panell de Pacients",
        visualitzaRealTime: "Visualitza en temps real l'estat de cada pacient i les dosis administrades.",
        estadistiquesDetallades: "Estadístiques Detallades",
        grafiquesInformes: "Gràfiques i informes amb les mètriques més importants del teu centre.",
        sistemaAuditoria: "Sistema d'Auditoria",
        registreComplet: "Registre complet de totes les accions per a complir la normativa vigent.",
        sistemaAlertes: "Sistema d'Alertes",
        notificacionsAutomaticas: "Notificacions automàtiques per a dosis crítiques i emergències.",
        creacioPacient: "Creació de Pacient",
        calculAutoma: "Selecciona isòtop i dosis - el sistema calcula automàticament l'activitat necessària",
        generacioInformes: "Generació d'Informes",
        creaExportaInformes: "Crea i exporta informes personalitzats per a cada departament.",
        seguretatTotal: "Seguretat Total",
        protocolsCertificats: "Protocols certificats",
        precisio: "+98% Precisió",
        dadesRealTime: "Dades en temps real",
        hospitalsConnectats: "Hospitals Connectats",
        pacientsMonitoritzats: "Pacients Monitoritzats",
        disponibilitat: "Disponibilitat",
        incidentsSeguretat: "Incidents de Seguretat",
        producte: "Producte",
        preus: "Preus",
        integracions: "Centres",
        actualitzacions: "Actualitzacions",
        empresa: "Empresa",
        sobreNosaltres: "Sobre Nosaltres",
        carreres: "Carreres",
        premsa: "Premsa",
        contacte: "Contacte",
        recursos: "Recursos",
        documentacio: "Documentació",
        api: "API",
        suport: "Suport",
        estatSistema: "Estat del Sistema",
        politicaPrivacitat: "Política de Privacitat",
        privacidadTitulo: "Privacitat i Termes",
        termesServei: "Termes de Servei",
        cookies: "Cookies",
        totsDretsReservats: "Tots els drets reservats.",
        cookiesTitol: "🍪 Cookies",
        cookiesMensaje: "Fem servir cookies pròpies per millorar la teva experiència i mantenir la teva sessió iniciada.",
        cookiesTipos: "essencials: sessió (1 any), seguretat. No fem servir cookies d'anàlisi o publicitat.",
        cookiesAceptar: "Acceptar",
        cookiesMasInfo: "Política de privacitat",
        privacidadActualizada: "Última actualització: Abril 2026",
        privacidadResponsable: "Responsable del tractament",
        privacidadDatos: "Les dades que tractem són:",
        privacidadRecopilacion: "Dades que recopilem",
        privacidadRecopilacionTexto: "Recopilem les següents dades:",
        privacidadDatosCuenta: "Dades del teu compte (nom, email, rol)",
        privacidadDatosPaciente: "Dades de pacients (nom, historial mèdic)",
        privacidadDatosLogs: "Logs d'accés i accions",
        privacidadUso: "Finalitat del tractament",
        privacidadUsoTexto: "Fem servir les teves dades per:",
        privacidadProporcionar: "Proporcionar el servei de gestió de radiofàrmacs",
        privacidadCumplir: "Complir amb obligacions legals (normativa sanitària)",
        privacidadMejorar: "Millorar el servei",
        privacidadCookies: "Cookies",
privacidadCookiesTexto: "Aquest lloc fa servir cookies pròpies:",
        privacidadSesion: "Cookie de sessió (1 any)",
        privacidadSesion_desc: "Manté la teva sessió iniciada. Se renova automàticament.",
        privacidadSeguridad: "Cookie de seguretat",
        privacidadSeguridad_desc: "Protegeix contra atacs CSRF",
        privacidadNoAnaliticos: "No fem servir cookies d'anàlisi ni publicitat",
        privacidadDerechos: "Els teus drets",
        privacidadDerechosTexto: "Tens dret a:",
        privacidadAcceso: "Accedir a les teves dades",
        privacidadRectificacion: "Rectificar dades incorrectes",
        privacidadSupresion: "Sol·licitar supressió",
        privacidadPortabilidad: "Rebre les teves dades en format portable",
        privacidadContacto: "Contacte",
        privacidadContactoTexto: "Per exercir els teus drets o qualsevol consulta:",
        volverInicio: "Tornar a l'inici",
        terminosTexto: "En accedir i fer servir aquest lloc, acceptes les següents condicions:",
        terminosAceptacion: "Acceptació",
        terminosAceptacionTxt: "En fer servir aquest servei acceptes complir aquests termes.",
        terminosUso: "Ús del servei",
        terminosUsoTxt: "El servei és per a gestió de radiofàrmacs en centres sanitaris.",
        terminosLimitacion: "Limitació de responsabilitat",
        terminosLimitacionTxt: "No ens fem responsables de l'ús indegut del programari.",
        terminosCambios: "Canvis",
        terminosCambiosTxt: "Podem modificar aquests termes sense previ avís.",
    },

    English: {
        // LOGIN
        bienvenidoAreaPrivada: "Welcome to the Private Area",
        accederCuentaGestion: "Access your management account",
        correoElectronico: "Email address...",
        contrasena: "Password...",
        recordarme: "Remember me",
        quieresCambiarContrasena: "Do you want to change your password?",
        iniciarSesion: "Sign in",
        
        // SIDEBAR
        radioisotopos: "Radioisotopes",
        paginaPrincipal: "Main Page",
        pacientes: "Patients",
        gestionUsuarios: "User Management",
        auditoria: "Audit",
        configuracion: "Settings",
        cerrarSesion: "Sign out",
        seguroCerrarSesion: "Are you sure you want to sign out?",
        cancelar: "Cancel",
        confirmar: "Confirm",
        
        // NAVBAR
        sistemaCentralClinico: "Clinical Central System",
        conexionCifrada: "End-to-end encrypted connection",
        avisosDelSistema: "System Notices",
        nuevos: "new",
        noHayNotificaciones: "No pending notifications",
        dr: "Dr.",
        especialista: "Specialist",
        perfilDelUsuario: "User profile",
        
        // HOMEPAGE
        inicio: "Home",
        resumenDispositivosPacientes: "Summary of device status and patients in treatment",
        pacientesActivos: "Active Patients",
        alertasDeHoy: "Today's Alerts",
        sincronizacion: "Synchronization",
        pacientesRevisadosRecientemente: "Recently reviewed patients",
        noHasRevisadoPacientes: "You haven't reviewed any patients recently.",
        ahoraMismo: "Right now",
        haceMin: "{min}min ago",
        haceH: "{horas}h ago",
        
        // PACIENTE PAGE
        gestionDePacientes: "Patient Management",
        gestionDispositivosTratamientos: "Device management and treatment supervision",
        anadirPaciente: "Add Patient",
        buscarPorTarjetaSanitaria: "Search by health card or name...",
        estadoTodos: "Status (All)",
        establePositivo: "Stable / Positive",
        ansiedadDepresion: "Anxiety / Depression",
        tratamientoTodos: "Treatment (All)",
        iodo: "Iodine",
        cobalto: "Cobalt",
        paciente: "PATIENT",
        estado: "STATUS",
        tratamiento: "TREATMENT",
        progreso: "PROGRESS",
        acciones: "ACTIONS",
        cargandoDatosClinicos: "Loading real clinical data...",
        verPerfil: "View Profile",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "New patient and treatment admission",
        registroSalutCatalunya: "Register to Salut de Catalunya file (CatSalut)",
        datosPersonales: "Personal Data (CatSalut)",
        nomCognoms: "Full Name",
        ejemploNombre: "Ex: John Smith",
        cipTargetaSanitaria: "CIP (Health Card)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Date of birth",
        hospitalReferencia: "Referral Hospital",
        tractamentRadioisotops: "Radioisotope Treatment",
        tipusRadioisotop: "Radioisotope Type",
        seleccionaIsotopo: "Select an isotope...",
        iodo131: "Iodine-131",
        lutecio177: "Lutetium-177",
        cobalto60: "Cobalt-60",
        dosiAdministrada: "Administered Dose",
        ejemploDosis: "Ex: 370",
        unitats: "Units",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Millicurie (mCi)",
        curis: "Curies (Ci)",
        dataHoraAdministracio: "Date and time of administration",
        sincronitzacioDispositius: "Device Synchronization",
        apropaSmartWatch: "Bring the patient's compatible SmartWatch close to start pairing.",
        buscarDispositiuNFC: "Search NFC device",
        resumAlta: "Admission Summary",
        consentimentInformat: "Informed consent recorded.",
        monitoritzacioZeroConfig: "Zero-Config monitoring active.",
        calculDecayefectiu: "Decay calculation according to Te effective.",
        confirmarIniciar: "Confirm and Start",
        porFavorCompletaCampos: "Please complete all technical fields.",
        sincronizandoCatsalut: "Synchronizing with CatSalut and generating report...",
altaCompletada: "Admission completed and report downloaded successfully.",
        errorProcesoAlta: "Error in admission process",
        aprobaSmartWatch: "Bring the patient's compatible SmartWatch close to start pairing.",
        buscandoDispositivo: "Searching for device...",
        relojVinculado: "Watch linked",
        errorVinculacionBluetooth: "Error linking Bluetooth",
        buscando: "Searching...",
        cambiarReloj: "Change Watch",
        vincularBluetooth: "Link Bluetooth",
         
        // PERFIL PACIENTE
        patientNoSeleccionado: "No patient selected",
        sinTratamiento: "No treatment",
        noVinculado: "Not linked",
        noVinculadoStatus: "Not linked",
        conectadoTransmitiendo: "Connected and transmitting",
        tractamentActiu: "Active Treatment",
        idPaciente: "Patient ID",
        dispositivoSmartwatch: "Smartwatch Device",
        bateria: "Battery",
        ultimaSinc: "Last sync",
        sincronizacionRemota: "Remote Synchronization",
        desconectar: "Disconnect",
        descargaBiometriaAutomatica: "Biometrics download is automatic from the patient's device.",
        progresoRadioterapia: "Radiotherapy Progress",
        cargaActiva: "Active Dose",
        consonanciaSalud: "Health Harmony",
        empujarConsejosReloj: "Push personalized advice to the watch screen",
        hidratacionBeberAgua: "Hydration: Drink 2L of water today",
        enviadoALas: "Sent at",
        seleccionarConsejo: "Select predefined advice...",
        evitarContactoNinos: "Avoid contact with children (24h)",
        beberLiquido: "Drink plenty of liquid",
        usarBanoExclusivo: "Use exclusive bathroom",
        enviarSmartWatch: "Send to SmartWatch",
        monitorEmocional: "Emotional Monitor (Weekly evolution)",
        esteEsEstadoDiario: "Patient's daily status (default 50%).",
        centroComunicacion: "Direct communication center",
        consultaGeneral: "General Inquiry",
        mensajeMedico: "Doctor's Message",
        noHayMensajesNuevos: "No new messages received today.",
        mensajeEnviadoExito: "Advice sent to Smartwatch successfully",
        errorEnviarConsejo: "Error sending advice",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "New Medical Staff Registration",
        completaDatosRegistrar: "Complete the data to register a new specialist.",
        datosAcceso: "Access Data (User)",
        nombreCompleto: "Full Name",
        ejemploNombreCompleto: "Ex. John Doe",
        correoCorporativo: "Corporate Email",
        ejemploCorreo: "john.doe@hospital.com",
        contrasenaTemporal: "Temporary Password",
        asignaContrasena: "Assign a password",
        hospitalReferenciaInput: "Referral Hospital",
        ejemploHospital: "Ex. General Hospital",
        datosProfesionales: "Professional Data (Physician)",
        especialidad: "Specialty",
        seleccionaEspecialidad: "Select a specialty...",
        oncologiaRadioterapica: "Radiation Oncology",
        medicinaNuclear: "Nuclear Medicine",
        radiologia: "Radiology",
        fisicaMedica: "Medical Physics",
        numeroColegiado: "License Number",
        ejemploColegiado: "Ex. 282893939",
        conectandoServidor: "Connecting to Render server...",
        medicoRegistrado: "Physician registered successfully.",
        errorComunicarServidor: "Error communicating with the server.",
        procesar: "Processing...",
        registrarMedicoSistema: "Register Physician in System",
        
        // CONFIGURACION
        configuracionSistema: "System Settings",
        ajustesCuentaAlertas: "Account settings, alerts and clinical preferences",
        datosCuenta: "Account Data",
        nombreProfesional: "Professional Name",
        correoElectronicoInput: "Email Address",
        especialidadInput: "Specialty",
        administracionSistemas: "System Administration",
        cambiarContrasena: "Change password",
        preferenciasSistema: "System Preferences",
        idiomaInterfaz: "Interface Language",
        zonaHoraria: "Time Zone",
        europaMadrid: "Europe/Madrid (CET)",
        europaLondres: "Europe/London (GMT)",
        notificacionesClinicas: "Clinical Notifications",
        bateriaBajaDispositivos: "Low battery on devices",
        avisarSmartWatchBaja: "Alert if drops below 15%",
        desconexionBiometrica: "Biometric disconnection",
        alertaPerdidaSenal: "Immediate alert if signal is lost",
        resumenSemanal: "Weekly summary",
        recibirInformeCorreo: "Receive report by email",
        alertaRadiacionSegura: "Safe Radiation Alert",
        avisarPacienteNiveles: "Alert at safe levels",
        anomaliaConstantesVitales: "Vital Signs Anomaly",
        notificarAlteraciones: "Notify cardiac alterations",
        falloSincronizacion: "Synchronization failure",
        avisarRelojNoEnvia: "Alert if watch doesn't send data (12h)",
        zonaSeguridad: "Security Zone",
        gestionarSesionesPermisos: "Manage sessions and permissions.",
        cerrarSesionTodosTerminales: "Sign out from all terminals",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Account Security",
        introduceContrasenaActual: "Enter your current and new password.",
        contrasenaActual: "Current password",
        nuevaContrasena: "New password",
        confirmarNuevaContrasena: "Confirm new password",
        contrasenasNoCoinciden: "New passwords don't match",
        contrasenaMinimoCaracteres: "Minimum 6 characters",
        contrasenaActualizadaExito: "Password updated!",
        volverAtras: "Go back",
        actualizarContrasena: "Update Password",
        
        // AUDITORIA
        panelAuditoria: "Audit Panel",
        controlAccesoSeguridad: "Access control and security",
        facultativo: "PHYSICIAN",
        especialidadHeader: "SPECIALTY",
        hospital: "HOSPITAL",
        estadoHeader: "STATUS",
        accionesSeguridad: "SECURITY ACTIONS",
        accediendoRegistros: "Accessing security records...",
        noHayFacultativos: "No registered physicians.",
        seguroCambiarEstado: "Change status to {nuevoEstado}?",
        exitoContrasenaActualizada: "Success: Password for {nombre} updated.",
        errorCambiarEstado: "Error changing status.",
        asignarNuevaContrasena: "New temporary password for {nombre}:",
        suspend: "Suspend",
        activar: "Activate",
        resetPWD: "Reset PWD",
        enviando: "Sending...",
        
        // ESTADOS
        estable: "Stable",
        activo: "ACTIVE",
        inactivo: "INACTIVE",

        // LANDING PAGE
        tecnologiaNuclear: "Advanced Nuclear Technology",
        gestioInteligent: "Smart Management of ",
        radiofarmacsClinics: "Clinical Radiopharmaceuticals",
        plataformaIntegral: "Comprehensive platform for hospitals and nuclear medicine centers. Real-time monitoring, complete traceability and certified security protocols.",
        demanaInformacio: "Request Information",
        veureDemo: "View Demo",
        caracteristiques: "Features",
        estatArtControl: "State of the art in hospital control",
        solucioCompleta: "A complete solution designed for nuclear medicine professionals, with the most advanced tools on the market.",
        monitoritzacioPacients: "Patient Monitoring",
        seguimentLogic: "Precise tracking of doses and administration history in real time. Interactive charts and personalized alerts.",
        alertesSeguretat: "Security Alerts",
        protocolAutematic: "Automatic protocol and emergency notifications for medical staff. Integration with hospital systems.",
        informesAuditoria: "Audit Reports",
        generacioAutomatitzada: "Automated traceability generation for regulatory compliance. Export in multiple certified formats.",
        analyticsAvancat: "Advanced Analytics",
        dashboardInteligent: "Intelligent dashboard with key metrics, historical trends and AI-based predictions.",
        complimentNormatiu: "Regulatory Compliance",
        normativaEuropea: "Full compliance with European and international regulations. ISO 9001 and ISO 27001 certifications.",
        xifratGrauMedic: "Medical-Grade Encryption",
        protectioDades: "Patient data protection with AES-256 encryption. Automatic backup and disaster recovery.",
        mesInformacio: "More information",
        solucionsIntegrals: "Integrated Solutions",
        dissenyatEquips: "Designed for excellent medical teams",
        plataformaIntegra: "Our platform integrates perfectly with your existing systems, providing a smooth and efficient experience for the entire team.",
        integracioApi: "Multi Center",
        connecteuSistemes: "Manage multiple centers from a single platform with centralized control.",
        suport247: "24/7 Support",
        equipEspecialistes: "Team of specialists available 24 hours to help you.",
        formacioInclosa: "Training Included",
        cursosCertificacio: "Certification courses for all medical team members included.",
        prepareuHospital: "Prepare your hospital for the future",
        contacteuNosaltres: "Get in touch with us for more information on how Radioisotopes can improve your center's management.",
        contactaNos: "Contact Us",
        respostaMenys24h: "Response in less than 24h",
        assessoriaPersonalitzada: "Personalized advice",
        senseCompromis: "No commitment",
        demo: "Demo",
        quePodeuMonitoritzar: "What you can monitor",
        descobrirFuncionalitats: "Discover the different functionalities of the radiopharmaceutical management system.",
        panellPacients: "Patient Dashboard",
        visualitzaRealTime: "View in real time the status of each patient and the doses administered.",
        estadistiquesDetallades: "Detailed Statistics",
        grafiquesInformes: "Charts and reports with the most important metrics for your center.",
        sistemaAuditoria: "Audit System",
        registreComplet: "Complete record of all actions to comply with current regulations.",
        sistemaAlertes: "Alert System",
        notificacionsAutomaticas: "Automatic notifications for critical doses and emergencies.",
        creacioPacient: "Patient Creation",
        calculAutoma: "Select isotope and dose - the system automatically calculates the required activity",
        generacioInformes: "Report Generation",
        creaExportaInformes: "Create and export personalized reports for each department.",
        seguretatTotal: "Total Security",
        protocolsCertificats: "Certified protocols",
        precisio: "+98% Accuracy",
        dadesRealTime: "Real-time data",
        hospitalsConnectats: "Connected Hospitals",
        pacientsMonitoritzats: "Monitored Patients",
        disponibilitat: "Availability",
        incidentsSeguretat: "Security Incidents",
        producte: "Product",
        preus: "Pricing",
        integracions: "Centers",
        actualitzacions: "Updates",
        empresa: "Company",
        sobreNosaltres: "About Us",
        carreres: "Careers",
        premsa: "Press",
        contacte: "Contact",
        recursos: "Resources",
        documentacio: "Documentation",
        api: "API",
        suport: "Support",
        estatSistema: "System Status",
        politicaPrivacitat: "Privacy Policy",
        privacidadTitulo: "Privacy & Terms",
        termesServei: "Terms of Service",
        cookies: "Cookies",
        totsDretsReservats: "All rights reserved.",
        cookiesTitol: "🍪 Cookies",
        cookiesMensaje: "We use our own cookies to improve your experience and keep you logged in.",
        cookiesTipos: "Essential: session (1 year), security. We don't use analytics or advertising cookies.",
        cookiesAceptar: "Accept",
        cookiesMasInfo: "Privacy policy",
        privacidadActualizada: "Last updated: April 2026",
        privacidadResponsable: "Data controller",
        privacidadDatos: "Data we process:",
        privacidadRecopilacion: "Data we collect",
        privacidadRecopilacionTexto: "We collect the following data:",
        privacidadDatosCuenta: "Account data (name, email, role)",
        privacidadDatosPaciente: "Patient data (name, medical history)",
        privacidadDatosLogs: "Access and action logs",
        privacidadUso: "Purpose of processing",
        privacidadUsoTexto: "We use your data to:",
        privacidadProporcionar: "Provide radiopharmaceutical management service",
        privacidadCumplir: "Comply with legal obligations (health regulations)",
        privacidadMejorar: "Improve the service",
        privacidadCookies: "Cookies",
        privacidadCookiesTexto: "This site uses our own cookies:",
        privacidadSesion: "Session cookie (1 year)",
        privacidadSesion_desc: "Keeps you logged in. Renews automatically.",
        privacidadSeguridad: "Security cookie",
        privacidadSeguridad_desc: "Protects against CSRF attacks",
        privacidadNoAnaliticos: "We don't use analytics or advertising cookies",
        privacidadDerechos: "Your rights",
        privacyDerechosTexto: "You have the right to:",
        privacidadAcceso: "Access your data",
        privacidadRectificacion: "Rectify incorrect data",
        privacidadSupresion: "Request deletion",
        privacidadPortabilidad: "Export your data",
        privacidadContacto: "Contact",
        privacidadContactoTexto: "To exercise your rights or any inquiry:",
        volverInicio: "Go back",
        terminosTexto: "By accessing and using this site, you accept the following terms:",
        terminosAceptacion: "Acceptance",
        terminosAceptacionTxt: "By using this service you agree to comply with these terms.",
        terminosUso: "Service use",
        terminosUsoTxt: "The service is for radiopharmaceutical management in healthcare centers.",
        terminosLimitacion: "Limitation of liability",
        terminosLimitacionTxt: "We are not responsible for misuse of the software.",
        terminosCambios: "Changes",
        terminosCambiosTxt: "We may modify these terms without prior notice.",
    }
};