export const textos = {
    Castellano: {
        // LOGIN
        bienvenidoAreaPrivada: "Bienvenido/a a la Área Privada",
        accederCuentaGestion: "Accede a tu cuenta de gestión",
        correoElectronico: "Correo electrónico...",
        contrasena: "Contraseña...",
        recordarme: "Recordarme",
        quieresCambiarContrasena: "¿Quieres cambiar tu contraseña?",
        iniciarSesion: "Iniciar sesión",
        
        // SIDEBAR
        radioisotopos: "Radioisótopos",
        paginaPrincipal: "Página Principal",
        pacientes: "Pacientes",
        gestionUsuarios: "Gestión Usuarios",
        auditoria: "Auditoría",
        configuracion: "Configuración",
        cerrarSesion: "Cerrar Sesión",
        seguroCerrarSesion: "¿Seguro que quieres cerrar sesión?",
        cancelar: "Cancelar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínico",
        conexionCifrada: "Conexión cifrada de extremo a extremo",
        avisosDelSistema: "Avisos del Sistema",
        nuevos: "nuevos",
        noHayNotificaciones: "No hay notificaciones pendientes",
        dr: "Dr.",
        especialista: "Especialista",
        
        // HOMEPAGE
        inicio: "Inicio",
        resumenDispositivosPacientes: "Resumen del estado de los dispositivos y pacientes en tratamiento",
        pacientesActivos: "Pacientes Activos",
        alertasDeHoy: "Alertas de hoy",
        sincronizacion: "Sincronización",
        pacientesRevisadosRecientemente: "Pacientes revisados recientemente",
        noHasRevisadoPacientes: "No has revisado pacientes recientemente.",
        ahoraMismo: "Ahora mismo",
        haceMin: "Hace {min}min",
        haceH: "Hace {horas}h",
        
        // PACIENTE PAGE
        gestionDePacientes: "Gestión de pacientes",
        gestionDispositivosTratamientos: "Gestión de dispositivos y supervisión de tratamientos",
        anadirPaciente: "Añadir Paciente",
        buscarPorTarjetaSanitaria: "Buscar por tarjeta sanitaria del paciente o nombre...",
        estadoTodos: "Estado (Todos)",
        establePositivo: "Estable / Positivo",
        ansiedadDepresion: "Ansiedad / Depresion",
        tratamientoTodos: "Tratamiento (Todos)",
        iodo: "Iodo",
        cobalto: "Cobalto",
        paciente: "PACIENTE",
        estado: "ESTADO",
        tratamiento: "TRATAMIENTO",
        progreso: "PROGRESO",
        acciones: "ACCIONES",
        cargandoDatosClinicos: "Cargando datos clínicos reales...",
        verPerfil: "Ver Perfil",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "Alta de nuevo paciente y tratamiento",
        registroSalutCatalunya: "Registro al fitxer de Salut de Catalunya (CatSalut)",
        datosPersonales: "Dades Personals (CatSalut)",
        nomCognoms: "Nom i Cognoms",
        ejemploNombre: "Ej: Marcos Góngora",
        cipTargetaSanitaria: "CIP (Targeta Sanitària)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Data de naixement",
        hospitalReferencia: "Hospital de Referència",
        tractamentRadioisotops: "Tractament de Radioisòtops",
        tipusRadioisotop: "Tipus de Radioisòtop",
        seleccionaIsotopo: "Selecciona un isòtop...",
        iodo131: "Iodo-131",
        lutecio177: "Lutecio-177",
        cobalto60: "Cobalto-60",
        dosiAdministrada: "Dosi Administrada",
        ejemploDosis: "Ej: 370",
        unitats: "Unitats",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Milicurio (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Data i hora d'administració",
        sincronitzacioDispositius: "Sincronització de Dispositius",
        apropaSmartWatch: "Apropa el SmartWatch compatible del pacient per iniciar la vinculació.",
        buscarDispositiuNFC: "Buscar dispositiu NFC",
        resumAlta: "Resum de l'Alta",
        consentimentInformat: "Consentiment informat registrat.",
        monitoritzacioZeroConfig: "Monitorització Zero-Config activa.",
        calculDecayefectiu: "Càlcul de decaïment segons Te efectiu.",
        confirmarIniciar: "Confirmar i Iniciar",
        porFavorCompletaCampos: "Por favor, completa todos los campos técnicos.",
        sincronizandoCatsalut: "Sincronizando con CatSalut y generando informe...",
        altaCompletada: "Alta completada e informe descargado con éxito.",
        errorProcesoAlta: "Error en el proceso de alta",
        
        // PERFIL PACIENTE
        patientNoSeleccionado: "Paciente no seleccionado",
        sinTratamiento: "Sin tratamiento",
        noVinculado: "No vinculado",
        noVinculadoStatus: "No vinculado",
        conectadoTransmitiendo: "Conectado y transmitiendo",
        tractamentActiu: "Tractament Actiu",
        idPaciente: "ID Paciente",
        dispositivoSmartwatch: "Dispositivo Smartwatch",
        bateria: "Batería",
        ultimaSinc: "Última sinc",
        sincronizacionRemota: "Sincronizacion Remota",
        desconectar: "Desconectar",
        descargaBiometriaAutomatica: "La descarga de biometría es automática desde el dispositivo del paciente.",
        progresoRadioterapia: "Progreso Radioterapia",
        cargaActiva: "Carga Activa",
        consonanciaSalud: "Consonancia de Salud",
        empujarConsejosReloj: "Empuja consejos personalizados a la pantalla del reloj",
        hidratacionBeberAgua: "Hidratar: Beber 2L de agua hoy",
        enviadoALas: "Enviado a las",
        seleccionarConsejo: "Seleccionar consejo predefinido...",
        evitarContactoNinos: "Evitar contacto con niños (24h)",
        beberLiquido: "Beber abundante líquido",
        usarBanoExclusivo: "Usar baño exclusivo",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolución semanal)",
        esteEsEstadoDiario: "Este es el estado diario del paciente, si no marca ningún estado saldrá a la mitad por defecto.",
        centroComunicacion: "Centro de comunicación directa",
        consultaGeneral: "Consulta General",
        noHayMensajesNuevos: "No se han recibido mensajes nuevos hoy.",
        mensajeEnviadoExito: "Consejo enviado al Smartwatch con éxito",
        errorEnviarConsejo: "Error al enviar el consejo",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "Alta de Nuevo Personal Médico",
        completaDatosRegistrar: "Completa los datos para registrar un nuevo especialista en el sistema.",
        datosAcceso: "Datos de Acceso (Usuario)",
        nombreCompleto: "Nombre Completo",
        ejemploNombreCompleto: "Ej. Carlos Ruiz",
        correoCorporativo: "Correo Electrónico Corporativo",
        ejemploCorreo: "carlos.ruiz@hospital.com",
        contrasenaTemporal: "Contraseña Temporal",
        asignaContrasena: "Asigna una contraseña",
        hospitalReferenciaInput: "Hospital de Referencia",
        ejemploHospital: "Ej. Hospital Clínic",
        datosProfesionales: "Datos Profesionales (Médico)",
        especialidad: "Especialidad",
        seleccionaEspecialidad: "Selecciona una especialidad...",
        oncologiaRadioterapica: "Oncología Radioterápica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiología",
        fisicaMedica: "Física Médica",
        numeroColegiado: "Número de Colegiado",
        ejemploColegiado: "Ej. 282893939",
        conectandoServidor: "Conectando con el servidor de Render...",
        medicoRegistrado: "Médico registrado correctamente.",
        errorComunicarServidor: "Error al comunicar con el servidor.",
        procesar: "Procesando...",
        registrarMedicoSistema: "Registrar Médico en el Sistema",
        
        // CONFIGURACION
        configuracionSistema: "Configuración del Sistema",
        ajustesCuentaAlertas: "Ajustes de cuenta, alertas y preferencias del entorno clínico",
        datosCuenta: "Datos de la Cuenta",
        nombreProfesional: "Nombre del Profesional",
        correoElectronicoInput: "Correo Electrónico",
        especialidadInput: "Especialidad",
        administracionSistemas: "Administración de Sistemas",
        cambiarContrasena: "Cambiar contraseña",
        preferenciasSistema: "Preferencias del Sistema",
        idiomaInterfaz: "Idioma de la interfaz",
        zonaHoraria: "Zona Horaria",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionesClinicas: "Notificaciones Clínicas",
        bateriaBajaDispositivos: "Batería baja en dispositivos",
        avisarSmartWatchBaja: "Avisar cuando un SmartWatch baje del 15%",
        desconexionBiometrica: "Desconexión biométrica",
        alertaPerdidaSenal: "Alerta inmediata si se pierde la señal",
        resumenSemanal: "Resumen semanal",
        recibirInformeCorreo: "Recibir informe de evolución por correo",
        alertaRadiacionSegura: "Alerta de Radiación Segura",
        avisarPacienteNiveles: "Avisar cuando el paciente alcance niveles seguros",
        anomaliaConstantesVitales: "Anomalía en Constantes Vitales",
        notificarAlteraciones: "Notificar alteraciones graves cardíacas",
        falloSincronizacion: "Fallo de sincronización",
        avisarRelojNoEnvia: "Avisar si un reloj no envía datos (12h)",
        zonaSeguridad: "Zona de Seguridad",
        gestionarSesionesPermisos: "Gestiona las sesiones activas y los permisos de acceso.",
        cerrarSesionTodosTerminales: "Cerrar sesión en todos los terminales",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Seguridad de la Cuenta",
        introduceContrasenaActual: "Introduce tu contraseña actual y la nueva que deseas utilizar.",
        contrasenaActual: "Contraseña actual",
        nuevaContrasena: "Nueva contraseña",
        confirmarNuevaContrasena: "Confirmar nueva contraseña",
        contrasenasNoCoinciden: "Las contraseñas nuevas no coinciden",
        contrasenaMinimoCaracteres: "La nueva contraseña debe tener al menos 6 caracteres",
        contrasenaActualizadaExito: "¡Contraseña actualizada con éxito!",
        volverAtras: "Volver atrás",
        actualizarContrasena: "Actualizar Contraseña",
        
        // AUDITORIA
        panelAuditoria: "Panel de Auditoría",
        controlAccesoSeguridad: "Control de acceso, seguridad y gestión de personal médico",
        facultativo: "FACULTATIVO",
        especialidadHeader: "ESPECIALIDAD",
        hospital: "HOSPITAL",
        estadoHeader: "ESTADO",
        accionesSeguridad: "ACCIONES SEGURIDAD",
        accediendoRegistros: "Accediendo a registros de seguridad...",
        noHayFacultativos: "No hay facultativos registrados.",
        seguroCambiarEstado: "¿Seguro que quieres cambiar el estado a {nuevoEstado}?",
        exitoContrasenaActualizada: "Éxito: Contraseña de {nombre} actualizada. El correo se enviará en segundo plano.",
        errorCambiarEstado: "Error al cambiar el estado.",
        asignarNuevaContrasena: "Asigna una nueva contraseña temporal para {nombre}:",
        suspend: "Suspender",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviando: "Enviando...",
        
        // ESTADOS
        estable: "Estable",
        activo: "ACTIVO",
        inactivo: "INACTIVO",
    },

    Catala: {
        // LOGIN
        bienvenidoAreaPrivada: "Benvingut/da a l'Àrea Privada",
        accederCuentaGestion: "Accedeix al teu compte de gestió",
        correoElectronico: "Correu electrònic...",
        contrasena: "Contrasenya...",
        recordarme: "Recorda'm",
        quieresCambiarContrasena: "Vols canviar la contrasenya?",
        iniciarSesion: "Iniciar sessió",
        
        // SIDEBAR
        radioisotopos: "Radioisòtops",
        paginaPrincipal: "Pàgina Principal",
        pacientes: "Pacients",
        gestionUsuarios: "Gestió Usuaris",
        auditoria: "Auditoria",
        configuracion: "Configuració",
        cerrarSesion: "Tancar Sessió",
        seguroCerrarSesion: "Segur que vols tancar sessió?",
        cancelar: "Cancel·lar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínic",
        conexionCifrada: "Connexió xifrada d'extrem a extrem",
        avisosDelSistema: "Avisos del Sistema",
        nous: "nous",
        noHayNotifications: "No hi ha notificacions pendents",
        dr: "Dr.",
        especialista: "Especialista",
        
        // HOMEPAGE
        inicio: "Inici",
        resumenDispositivosPacients: "Resum de l'estat dels dispositius i pacients en tractament",
        pacientsActius: "Pacients Actius",
        alertsDAvui: "Alertes d'avui",
        sincronitzacio: "Sincronització",
        pacientsRevisatsRecent: "Pacients revisats recentment",
        noHasRevisatPacients: "No has revisat pacients recentment.",
        araMateix: "Ara mateix",
        faMin: "Fa {min}min",
        faH: "Fa {hores}h",
        
        // PACIENTE PAGE
        gestioPacients: "Gestió de pacients",
        gestioDispositiusTractaments: "Gestió de dispositius i supervisió de tractaments",
        afegirPacient: "Afegir Pacient",
        buscarTargetaSanitaria: "Buscar per targeta sanitària del pacient o nom...",
        estatTots: "Estat (Tots)",
        establePositiu: "Estable / Positiu",
        ansietatDepressio: "Ansietat / Depressió",
        tractamentTots: "Tractament (Tots)",
        iode: "Iode",
        cobalt: "Cobalt",
        pacient: "PACIENT",
        estat: "ESTAT",
        tractament: "TRACTAMENT",
        progrés: "PROGRÉS",
        accions: "ACCIONS",
        carregantDadesCliniques: "Carregant dades clíniques reals...",
        veurePerfil: "Veure Perfil",
        
        // CREAR PACIENTE
        altaNouPacient: "Alta de nou pacient i tractament",
        registreSalutCatalunya: "Registre al fitxer de Salut de Catalunya (CatSalut)",
        dadesPersonals: "Dades Personals (CatSalut)",
        nomCognoms: "Nom i Cognoms",
        exempleNom: "Ex: Marc García",
        cipTargetaSanitaria: "CIP (Targeta Sanitària)",
        exempleCIP: "FARR000000000",
        dataNaixement: "Data de naixement",
        hospitalReferencia: "Hospital de Referència",
        tractamentRadioisotops: "Tractament de Radioisòtops",
        tipusRadioisotop: "Tipus de Radioisòtop",
        seleccionaIsotop: "Selecciona un isòtop...",
        iode131: "Iode-131",
        luteci177: "Luteci-177",
        cobalt60: "Cobalt-60",
        dosiAdministrada: "Dosi Administrada",
        exempleDosi: "Ex: 370",
        unitats: "Unitats",
        megaBecquerels: "Mega becquerels (MBq)",
        milicuri: "Milicuri (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Data i hora d'administració",
        sincronitzacioDispositius: "Sincronització de Dispositius",
        apropaSmartWatch: "Aprop el SmartWatch compatible del pacient per iniciar la vinculació.",
        buscarDispositiuNFC: "Buscar dispositiu NFC",
        resumAlta: "Resum de l'Alta",
        consentimentInformat: "Consentiment informat registrat.",
        monitoritzacioZeroConfig: "Monitorització Zero-Config activa.",
        calculDecayefectiu: "Càlcul de decaïment segons Te efectiu.",
        confirmarIniciar: "Confirmar i Iniciar",
        perFavorCompletaCamps: "Si us plau, completa tots els camps tècnics.",
        sincronitzantCatsalut: "Sincronitzant amb CatSalut i generant informe...",
        altaCompletada: "Alta completada i informe descargat amb èxit.",
        errorProcesAlta: "Error en el procés d'alta",
        
        // PERFIL PACIENTE
        pacientNoSeleccionat: "Pacient no seleccionat",
        senseTractament: "Sense tractament",
        noVinculat: "No vinculat",
        noVinculatStatus: "No vinculat",
        conectatTransmetent: "Connexió i transmissió",
        tractamentActiu: "Tractament Actiu",
        idPacient: "ID Pacient",
        dispositiuSmartwatch: "Dispositiu Smartwatch",
        bateria: "Bateria",
        ultimSinc: "Últim sinc",
        sincronitzacioRemota: "Sincronització Remota",
        desconectar: "Desconnectar",
        descarcaBiometriaAutomatica: "La descàrrega de biometria és automàtica des del dispositiu del pacient.",
        progresRadioterapia: "Progess Radioteràpia",
        cargaActiva: "Càrrega Activa",
        consonanciaSalut: "Concordança de Salut",
        impulsarConsellsRellotge: "Empusha consells personalitzats a la pantalla del rellotge",
        hidratacioBeureAigua: "Hidratació: Beure 2L d'aigua avui",
        enviatALes: "Enviat a les",
        seleccionarConsell: "Seleccionar consell predefinit...",
        evitarContacteNens: "Evitar contacte amb nens (24h)",
        begudaLiquida: "Beure líquid abundant",
        usarLavaboExclusiu: "Usar lavabo exclusiu",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolució setmanal)",
        aquiEstatDiariPacient: "Aquest és l'estat diari del pacient, si no marca cap estat sortirà a la meitat per defecte.",
        centreComunicacio: "Centre de comunicació directa",
        consultaGeneral: "Consulta General",
        noHiHaMissatgesNous: "No s'han rebut missatges nous avui.",
        consellEnviatExit: "Consell enviat al Smartwatch amb èxit",
        errorEnviarConsell: "Error en enviar el consell",
        
        // GESTION USUARIO
        altaNouPersonalMedic: "Alta de Nou Personal Mèdic",
        completaDadesRegistrar: "Completa les dades per registrar un nou especialista al sistema.",
        dadesAcces: "Dades d'Accés (Usuari)",
        nomComplet: "Nom Complet",
        exempleNomComplet: "Ex. Carles Ruiz",
        correuCorporatiu: "Correu Corporatiu",
        exempleCorreu: "carles.ruiz@hospital.com",
        contrasenyaTemporal: "Contrasenya Temporal",
        assignsContrasenya: "Assigna una contrasenya",
        hospitalReferenciaInput: "Hospital de Referència",
        exempleHospital: "Ex. Hospital Clínic",
        dadesProfessionals: "Dades Professionals (Metge)",
        especialitat: "Especialitat",
        seleccionaEspecialitat: "Selecciona una especialitat...",
        oncologiaRadioterapica: "Oncologia Radioteràpica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiologia",
        fisicaMedica: "Física Mèdica",
        numeroColegiat: "Número de Col·legiat",
        exempleColegiat: "Ex. 282893939",
        conectantServidor: "Connectant amb el servidor de Render...",
        metgeRegistrat: "Metge registrat correctament.",
        errorComunicarServidor: "Error al comunicar amb el servidor.",
        processant: "Processant...",
        registrarMetgeSistema: "Registrar Metge al Sistema",
        
        // CONFIGURACIÓ
        configuracioSistema: "Configuració del Sistema",
        ajustosCompteAlertes: "Ajustos de compte, alertes i preferències de l'entorn clínic",
        dadesCompte: "Dades del Compte",
        nomProfessional: "Nom del Professional",
        correuElectronic: "Correu Electrònic",
        especialitatInput: "Especialitat",
        administracioSistemes: "Administració de Sistemes",
        canviarContrasenya: "Canviar contrasenya",
        preferenciesSistema: "Preferències del Sistema",
        idiomaInterficie: "Idioma de la interfície",
        zonaHoraria: "Zona Horària",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionsCliniques: "Notificacions Clíniques",
        bateriaBaixaDispositius: "Bateria baixa en dispositius",
        avisarSmartWatchBaixa: "Avisar quan un SmartWatch baixi del 15%",
        desconexioBiometrica: "Desconnexió biomètrica",
        alertaPerduaSenal: "Alerta immediata si es perd el senyal",
        resumSetmanal: "Resum setmanal",
        rebreInformeCorreu: "Rebre informe d'evolució per correu",
        alertaRadiacioSegura: "Alerta de Radiació Segura",
        avisarPacientNivells: "Avisar quan el pacient arribi a nivells segurs",
        anomaliaConstantsVitals: "Anomalia en Constants Vitals",
        notificarAlteracions: "Notificar alteracions greus cardíaques",
        falloSincronitzacio: "Fallada de sincronització",
        avisarRellotgeNoEnvia: "Avisar si un rellotge no envia dades (12h)",
        zonaSeguretat: "Zona de Seguretat",
        gestionarSessionsPermisos: "Gestiona les sessions actives i els permisos d'accés.",
        tancarSessioTotsTerminals: "Tancar sessió a tots els terminals",
        
        // CANVIAR PASSWORD
        seguretatCompte: "Seguretat del Compte",
        introdueixContrasenyaActual: "Introdueix la contrasenya actual i la nova que vulguis utilitzar.",
        contrasenyaActual: "Contrasenya actual",
        novaContrasenya: "Nova contrasenya",
        confirmarNovaContrasenya: "Confirmar nova contrasenya",
        contrasenyesNoCoincideixen: "Les contrasenyes no coincideixen",
        contrasenyaMinimCaracters: "La nova contrasenya ha de tenir almenys 6 caràcters",
        contrasenyaActualitzadaExit: "¡Contrasenya actualitzada amb èxit!",
        tornarEnrere: "Tornar enrere",
        actualitzarContrasenya: "Actualitzar Contrasenya",
        
        // AUDITORIA
        panelAuditoria: "Panel d'Auditoria",
        controlAccesSeguretat: "Control d'accés, seguretat i gestió de personal mèdic",
        facultatiu: "FACULTATIU",
        especialitatHeader: "ESPECIALITAT",
        hospital: "HOSPITAL",
        estatHeader: "ESTAT",
        accionsSeguretat: "ACCIONS SEGURETAT",
        accedintRegistres: "Accedint a registres de seguretat...",
        noHiHaFacultatius: "No hi ha facultatius registrats.",
        segurCanviarEstat: "Segur que vols canviar l'estat a {nouEstat}?",
        exitContrasenyaActualitzada: "Èxit: Contrasenya de {nom} actualitzada. El correu s'enviarà en segon pla.",
        errorCanviarEstat: "Error al canviar l'estat.",
        assignarNovaContrasenya: "Assigna una nova contrasenya temporal per {nom}:",
        suspendre: "Suspendre",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviant: "Enviant...",
        
        // ESTATS
        estable: "Estable",
        actiu: "ACTIU",
        inactiu: "INACTIU",
    },

    English: {
        // LOGIN
        bienvenidoAreaPrivada: "Welcome to the Private Area",
        accederCuentaGestion: "Access your management account",
        correoElectronico: "Email address...",
        contrasena: "Password...",
        recordarme: "Remember me",
        quieresCambiarContrasena: "Do you want to change your password?",
        iniciarSesion: "Sign in",
        
        // SIDEBAR
        radioisotopos: "Radioisotopes",
        paginaPrincipal: "Main Page",
        pacientes: "Patients",
        gestionUsuarios: "User Management",
        auditoria: "Audit",
        configuracion: "Settings",
        cerrarSesion: "Sign out",
        seguroCerrarSesion: "Are you sure you want to sign out?",
        cancelar: "Cancel",
        confirmar: "Confirm",
        
        // NAVBAR
        sistemaCentralClinico: "Clinical Central System",
        conexionCifrada: "End-to-end encrypted connection",
        avisosDelSistema: "System Notices",
        nuevos: "new",
        noHayNotificaciones: "No pending notifications",
        dr: "Dr.",
        especialista: "Specialist",
        
        // HOMEPAGE
        inicio: "Home",
        resumenDispositivosPacientes: "Summary of device status and patients in treatment",
        pacientesActivos: "Active Patients",
        alertasDeHoy: "Today's Alerts",
        sincronizacion: "Synchronization",
        pacientesRevisadosRecientemente: "Recently reviewed patients",
        noHasRevisadoPacientes: "You haven't reviewed any patients recently.",
        ahoraMismo: "Right now",
        haceMin: "{min}min ago",
        haceH: "{horas}h ago",
        
        // PACIENTE PAGE
        gestionDePacientes: "Patient Management",
        gestionDispositivosTratamientos: "Device management and treatment supervision",
        anadirPaciente: "Add Patient",
        buscarPorTarjetaSanitaria: "Search by health card or name...",
        estadoTodos: "Status (All)",
        establePositivo: "Stable / Positive",
        ansiedadDepresion: "Anxiety / Depression",
        tratamientoTodos: "Treatment (All)",
        iodo: "Iodine",
        cobalto: "Cobalt",
        paciente: "PATIENT",
        estado: "STATUS",
        tratamiento: "TREATMENT",
        progreso: "PROGRESS",
        acciones: "ACTIONS",
        cargandoDatosClinicos: "Loading real clinical data...",
        verPerfil: "View Profile",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "New patient and treatment admission",
        registroSalutCatalunya: "Register to Salut de Catalunya file (CatSalut)",
        datosPersonales: "Personal Data (CatSalut)",
        nomCognoms: "Full Name",
        ejemploName: "Ex: John Smith",
        cipTargetaSanitaria: "CIP (Health Card)",
        exampleCIP: "FARR000000000",
        dataNaixement: "Date of birth",
        hospitalReferencia: "Referral Hospital",
        tractamentRadioisotops: "Radioisotope Treatment",
        tipusRadioisotop: "Radioisotope Type",
        seleccionaIsotopo: "Select an isotope...",
        iodo131: "Iodine-131",
        lutecio177: "Lutetium-177",
        cobalto60: "Cobalt-60",
        dosiAdministrada: "Administered Dose",
        exempleDosis: "Ex: 370",
        unitats: "Units",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Millicurie (mCi)",
        curis: "Curies (Ci)",
        dataHoraAdministracio: "Date and time of administration",
        sincronitzacioDispositius: "Device Synchronization",
        approchaSmartWatch: "Bring the patient's compatible SmartWatch close to start pairing.",
        buscarDispositiuNFC: "Search NFC device",
        resumAlta: "Admission Summary",
        consentimentInformat: "Informed consent recorded.",
        monitoritzacioZeroConfig: "Zero-Config monitoring active.",
        calculDecayefectiu: "Decay calculation according to Te effective.",
        confirmarIniciar: "Confirm and Start",
        porFavorCompletaCampos: "Please complete all technical fields.",
        sincronizandoCatsalut: "Synchronizing with CatSalut and generating report...",
        altaCompletada: "Admission completed and report downloaded successfully.",
        errorProcesoAlta: "Error in admission process",
        
        // PERFIL PACIENTE
        patientNoSeleccionado: "No patient selected",
        sinTratamiento: "No treatment",
        noVinculado: "Not linked",
        noVinculadoStatus: "Not linked",
        conectadoTransmitiendo: "Connected and transmitting",
        tractamentActiu: "Active Treatment",
        idPaciente: "Patient ID",
        dispositivoSmartwatch: "Smartwatch Device",
        bateria: "Battery",
        ultimaSinc: "Last sync",
        sincronizacionRemota: "Remote Synchronization",
        desconectar: "Disconnect",
        descargaBiometriaAutomatica: "Biometrics download is automatic from the patient's device.",
        progresoRadioterapia: "Radiotherapy Progress",
        cargaActiva: "Active Dose",
        consonanciaSalud: "Health Harmony",
        empujarConsejosReloj: "Push personalized advice to the watch screen",
        hidratacionBeberAgua: "Hydration: Drink 2L of water today",
        enviadoALas: "Sent at",
        seleccionarConsejo: "Select predefined advice...",
        evitarContactoNinos: "Avoid contact with children (24h)",
        beberLiquido: "Drink plenty of liquid",
        usarBanoExclusivo: "Use exclusive bathroom",
        enviarSmartWatch: "Send to SmartWatch",
        monitorEmocional: "Emotional Monitor (Weekly evolution)",
        esteEsEstadoDiario: "This is the patient's daily status, if they don't mark any status it will default to half.",
        centroComunicacion: "Direct communication center",
        consultaGeneral: "General Inquiry",
        noHayMensajesNuevos: "No new messages received today.",
        mensajeEnviadoExito: "Advice sent to Smartwatch successfully",
        errorEnviarConsejo: "Error sending advice",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "New Medical Staff Registration",
        completaDatosRegistrar: "Complete the data to register a new specialist in the system.",
        datosAcceso: "Access Data (User)",
        nombreCompleto: "Full Name",
        ejemploNombreCompleto: "Ex. John Doe",
        correoCorporativo: "Corporate Email",
        ejemploCorreo: "john.doe@hospital.com",
        contrasenaTemporal: "Temporary Password",
        asignaContrasena: "Assign a password",
        hospitalReferenciaInput: "Referral Hospital",
        ejemploHospital: "Ex. General Hospital",
        datosProfesionales: "Professional Data (Physician)",
        especialidad: "Specialty",
        seleccionaEspecialidad: "Select a specialty...",
        oncologiaRadioterapica: "Radiation Oncology",
        medicinaNuclear: "Nuclear Medicine",
        radiologia: "Radiology",
        fisicaMedica: "Medical Physics",
        numeroColegiado: "License Number",
        ejemploColegiado: "Ex. 282893939",
        conectandoServidor: "Connecting to Render server...",
        medicoRegistrado: "Physician registered successfully.",
        errorComunicarServidor: "Error communicating with the server.",
        procesar: "Processing...",
        registrarMedicoSistema: "Register Physician in System",
        
        // CONFIGURACION
        configuracionSistema: "System Settings",
        ajustesCuentaAlertas: "Account settings, alerts and clinical environment preferences",
        datosCuenta: "Account Data",
        nombreProfesional: "Professional Name",
        correoElectronicoInput: "Email Address",
        especialidadInput: "Specialty",
        administracionSistemas: "System Administration",
        cambiarContrasena: "Change password",
        preferenciasSistema: "System Preferences",
        idiomaInterfaz: "Interface Language",
        zonaHoraria: "Time Zone",
        europaMadrid: "Europe/Madrid (CET)",
        europaLondres: "Europe/London (GMT)",
        notificacionesClinicas: "Clinical Notifications",
        bateriaBajaDispositivos: "Low battery on devices",
        avisarSmartWatchBaja: "Alert when SmartWatch drops below 15%",
        desconexionBiometrica: "Biometric disconnection",
        alertaPerdidaSenal: "Immediate alert if signal is lost",
        resumenSemanal: "Weekly summary",
        recibirInformeCorreo: "Receive evolution report by email",
        alertaRadiacionSegura: "Safe Radiation Alert",
        avisarPacienteNiveles: "Alert when patient reaches safe levels",
        anomaliaConstantesVitales: "Vital Signs Anomaly",
        notificarAlteraciones: "Notify severe cardiac alterations",
        falloSincronizacion: "Synchronization failure",
        avisarRelojNoEnvia: "Alert if watch doesn't send data (12h)",
        zonaSeguridad: "Security Zone",
        gestionarSesionesPermisos: "Manage active sessions and access permissions.",
        cerrarSesionTodosTerminales: "Sign out from all terminals",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Account Security",
        introduceContrasenaActual: "Enter your current password and the new one you want to use.",
        contrasenaActual: "Current password",
        nuevaContrasena: "New password",
        confirmarNuevaContrasena: "Confirm new password",
        contrasenasNoCoinciden: "New passwords don't match",
        contrasenaMinimoCaracteres: "New password must be at least 6 characters",
        contrasenaActualizadaExito: "Password updated successfully!",
        volverAtras: "Go back",
        actualizarContrasena: "Update Password",
        
        // AUDITORIA
        panelAuditoria: "Audit Panel",
        controlAccesoSeguridad: "Access control, security and medical staff management",
        facultativo: "PHYSICIAN",
        especialidadHeader: "SPECIALTY",
        hospital: "HOSPITAL",
        estadoHeader: "STATUS",
        accionesSeguridad: "SECURITY ACTIONS",
        accediendoRegistros: "Accessing security records...",
        noHayFacultativos: "No registered physicians.",
        seguroCambiarEstado: "Are you sure you want to change status to {nuevoEstado}?",
        exitoContrasenaActualizada: "Success: Password for {nombre} updated. Email will be sent in background.",
        errorCambiarEstado: "Error changing status.",
        asignarNuevaContrasena: "Assign a new temporary password for {nombre}:",
        suspend: "Suspend",
        activate: "Activate",
        resetPWD: "Reset PWD",
        sending: "Sending...",
        
        // ESTADOS
        estable: "Stable",
        activo: "ACTIVE",
        inactivo: "INACTIVE",
    }
};
