export const textos = {
    Castellano: {
        // LOGIN
        bienvenidoAreaPrivada: "Bienvenido/a a la Área Privada",
        accederCuentaGestion: "Accede a tu cuenta de gestión",
        correoElectronico: "Correo electrónico...",
        contrasena: "Contraseña...",
        recordarme: "Recordarme",
        quieresCambiarContrasena: "¿Quieres cambiar tu contraseña?",
        iniciarSesion: "Iniciar sesión",
        
        // SIDEBAR
        radioisotopos: "Radioisótopos",
        paginaPrincipal: "Página Principal",
        pacientes: "Pacientes",
        gestionUsuarios: "Gestión Usuarios",
        auditoria: "Auditoría",
        configuracion: "Configuración",
        cerrarSesion: "Cerrar Sesión",
        seguroCerrarSesion: "¿Seguro que quieres cerrar sesión?",
        cancelar: "Cancelar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínico",
        conexionCifrada: "Conexión cifrada de extremo a extremo",
        avisosDelSistema: "Avisos del Sistema",
        nuevos: "nuevos",
        noHayNotificaciones: "No hay notificaciones pendientes",
        dr: "Dr.",
        especialista: "Especialista",
        perfilDelUsuario : "Perfil de Usuario",
        
        // HOMEPAGE
        inicio: "Inicio",
        resumenDispositivosPacientes: "Resumen del estado de los dispositivos y pacientes en tratamiento",
        pacientesActivos: "Pacientes Activos",
        alertasDeHoy: "Alertas de hoy",
        sincronizacion: "Sincronización",
        pacientesRevisadosRecientemente: "Pacientes revisados recientemente",
        noHasRevisadoPacientes: "No has revisado pacientes recientemente.",
        ahoraMismo: "Ahora mismo",
        haceMin: "Hace {min}min",
        haceH: "Hace {horas}h",
        
        // PACIENTE PAGE
        gestionDePacientes: "Gestión de pacientes",
        gestionDispositivosTratamientos: "Gestión de dispositivos y supervisión de tratamientos",
        anadirPaciente: "Añadir Paciente",
        buscarPorTarjetaSanitaria: "Buscar por tarjeta sanitaria del paciente o nombre...",
        estadoTodos: "Estado (Todos)",
        establePositivo: "Estable / Positivo",
        ansiedadDepresion: "Ansiedad / Depresión",
        tratamientoTodos: "Tratamiento (Todos)",
        iodo: "Iodo",
        cobalto: "Cobalto",
        paciente: "PACIENTE",
        estado: "ESTADO",
        tratamiento: "TRATAMIENTO",
        progreso: "PROGRESO",
        acciones: "ACCIONES",
        cargandoDatosClinicos: "Cargando datos clínicos reales...",
        verPerfil: "Ver Perfil",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "Alta de nuevo paciente y tratamiento",
        registroSalutCatalunya: "Registro al fitxer de Salut de Catalunya (CatSalut)",
        datosPersonales: "Datos Personales (CatSalut)",
        nomCognoms: "Nombre y Apellidos",
        ejemploNombre: "Ej: Marcos Góngora",
        cipTargetaSanitaria: "CIP (Tarjeta Sanitaria)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Fecha de nacimiento",
        hospitalReferencia: "Hospital de Referencia",
        tractamentRadioisotops: "Tratamiento de Radioisótopos",
        tipusRadioisotop: "Tipo de Radioisótopo",
        seleccionaIsotopo: "Selecciona un isótopo...",
        iodo131: "Iodo-131",
        lutecio177: "Lutecio-177",
        cobalto60: "Cobalto-60",
        dosiAdministrada: "Dosis Administrada",
        ejemploDosis: "Ej: 370",
        unitats: "Unidades",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Milicurio (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Fecha y hora de administración",
        sincronitzacioDispositius: "Sincronización de Dispositivos",
        apropaSmartWatch: "Acerca el SmartWatch compatible del paciente para iniciar la vinculación.",
        buscarDispositiuNFC: "Buscar dispositivo NFC",
        resumAlta: "Resumen del Alta",
        consentimentInformat: "Consentimiento informado registrado.",
        monitoritzacioZeroConfig: "Monitorización Zero-Config activa.",
        calculDecayefectiu: "Cálculo de decaimiento según Te efectivo.",
        confirmarIniciar: "Confirmar e Iniciar",
        porFavorCompletaCampos: "Por favor, completa todos los campos técnicos.",
        sincronizandoCatsalut: "Sincronizando con CatSalut y generando informe...",
        altaCompletada: "Alta completada e informe descargado con éxito.",
        errorProcesoAlta: "Error en el proceso de alta",
        
        // PERFIL PACIENTE
        patientNoSeleccionado: "Paciente no seleccionado",
        sinTratamiento: "Sin tratamiento",
        noVinculado: "No vinculado",
        noVinculadoStatus: "No vinculado",
        conectadoTransmitiendo: "Conectado y transmitiendo",
        tractamentActiu: "Tratamiento Activo",
        idPaciente: "ID Paciente",
        dispositivoSmartwatch: "Dispositivo Smartwatch",
        bateria: "Batería",
        ultimaSinc: "Última sinc",
        sincronizacionRemota: "Sincronización Remota",
        desconectar: "Desconectar",
        descargaBiometriaAutomatica: "La descarga de biometría es automática desde el dispositivo del paciente.",
        progresoRadioterapia: "Progreso Radioterapia",
        cargaActiva: "Carga Activa",
        consonanciaSalud: "Consonancia de Salud",
        empujarConsejosReloj: "Envía consejos personalizados a la pantalla del reloj",
        hidratacionBeberAgua: "Hidratar: Beber 2L de agua hoy",
        enviadoALas: "Enviado a las",
        seleccionarConsejo: "Seleccionar consejo predefinido...",
        evitarContactoNinos: "Evitar contacto con niños (24h)",
        beberLiquido: "Beber abundante líquido",
        usarBanoExclusivo: "Usar baño exclusivo",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolución semanal)",
        esteEsEstadoDiario: "Estado diario del paciente (defecto 50%).",
        centroComunicacion: "Centro de comunicación directa",
        consultaGeneral: "Consulta General",
        noHayMensajesNuevos: "No se han recibido mensajes nuevos hoy.",
        mensajeEnviadoExito: "Consejo enviado al Smartwatch con éxito",
        errorEnviarConsejo: "Error al enviar el consejo",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "Alta de Nuevo Personal Médico",
        completaDatosRegistrar: "Completa los datos para registrar un nuevo especialista.",
        datosAcceso: "Datos de Acceso (Usuario)",
        nombreCompleto: "Nombre Completo",
        ejemploNombreCompleto: "Ej. Carlos Ruiz",
        correoCorporativo: "Correo Electrónico Corporativo",
        ejemploCorreo: "carlos.ruiz@hospital.com",
        contrasenaTemporal: "Contraseña Temporal",
        asignaContrasena: "Asigna una contraseña",
        hospitalReferenciaInput: "Hospital de Referencia",
        ejemploHospital: "Ej. Hospital Clínic",
        datosProfesionales: "Datos Profesionales (Médico)",
        especialidad: "Especialidad",
        seleccionaEspecialidad: "Selecciona una especialidad...",
        oncologiaRadioterapica: "Oncología Radioterápica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiología",
        fisicaMedica: "Física Médica",
        numeroColegiado: "Número de Colegiado",
        ejemploColegiado: "Ej. 282893939",
        conectandoServidor: "Conectando con el servidor de Render...",
        medicoRegistrado: "Médico registrado correctamente.",
        errorComunicarServidor: "Error al comunicar con el servidor.",
        procesar: "Procesando...",
        registrarMedicoSistema: "Registrar Médico en el Sistema",
        
        // CONFIGURACION
        configuracionSistema: "Configuración del Sistema",
        ajustesCuentaAlertas: "Ajustes de cuenta, alertas y preferencias",
        datosCuenta: "Datos de la Cuenta",
        nombreProfesional: "Nombre del Profesional",
        correoElectronicoInput: "Correo Electrónico",
        especialidadInput: "Especialidad",
        administracionSistemas: "Administración de Sistemas",
        cambiarContrasena: "Cambiar contraseña",
        preferenciasSistema: "Preferencias del Sistema",
        idiomaInterfaz: "Idioma de la interfaz",
        zonaHoraria: "Zona Horaria",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionesClinicas: "Notificaciones Clínicas",
        bateriaBajaDispositivos: "Batería baja en dispositivos",
        avisarSmartWatchBaja: "Avisar si baja del 15%",
        desconexionBiometrica: "Desconexión biométrica",
        alertaPerdidaSenal: "Alerta inmediata si se pierde señal",
        resumenSemanal: "Resumen semanal",
        recibirInformeCorreo: "Recibir informe por correo",
        alertaRadiacionSegura: "Alerta de Radiación Segura",
        avisarPacienteNiveles: "Avisar en niveles seguros",
        anomaliaConstantesVitales: "Anomalía en Constantes Vitales",
        notificarAlteraciones: "Notificar alteraciones cardíacas",
        falloSincronizacion: "Fallo de sincronización",
        avisarRelojNoEnvia: "Avisar si no envía datos (12h)",
        zonaSeguridad: "Zona de Seguridad",
        gestionarSesionesPermisos: "Gestiona sesiones y permisos.",
        cerrarSesionTodosTerminales: "Cerrar sesión en todos los terminales",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Seguridad de la Cuenta",
        introduceContrasenaActual: "Introduce tu contraseña actual y la nueva.",
        contrasenaActual: "Contraseña actual",
        nuevaContrasena: "Nueva contraseña",
        confirmarNuevaContrasena: "Confirmar nueva contraseña",
        contrasenasNoCoinciden: "Las contraseñas nuevas no coinciden",
        contrasenaMinimoCaracteres: "Mínimo 6 caracteres",
        contrasenaActualizadaExito: "¡Contraseña actualizada!",
        volverAtras: "Volver atrás",
        actualizarContrasena: "Actualizar Contraseña",
        
        // AUDITORIA
        panelAuditoria: "Panel de Auditoría",
        controlAccesoSeguridad: "Control de acceso y seguridad",
        facultativo: "FACULTATIVO",
        especialidadHeader: "ESPECIALIDAD",
        hospital: "HOSPITAL",
        estadoHeader: "ESTADO",
        accionesSeguridad: "ACCIONES SEGURIDAD",
        accediendoRegistros: "Accediendo a registros...",
        noHayFacultativos: "No hay facultativos.",
        seguroCambiarEstado: "¿Cambiar estado a {nuevoEstado}?",
        exitoContrasenaActualizada: "Éxito: Contraseña de {nombre} actualizada.",
        errorCambiarEstado: "Error al cambiar el estado.",
        asignarNuevaContrasena: "Nueva contraseña para {nombre}:",
        suspend: "Suspender",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviando: "Enviando...",
        
        // ESTADOS
        estable: "Estable",
        activo: "ACTIVO",
        inactivo: "INACTIVO",
    },

    Catala: {
        // LOGIN
        bienvenidoAreaPrivada: "Benvingut/da a l'Àrea Privada",
        accederCuentaGestion: "Accedeix al teu compte de gestió",
        correoElectronico: "Correu electrònic...",
        contrasena: "Contrasenya...",
        recordarme: "Recorda'm",
        quieresCambiarContrasena: "Vols canviar la contrasenya?",
        iniciarSesion: "Iniciar sessió",
        
        // SIDEBAR
        radioisotopos: "Radioisòtops",
        paginaPrincipal: "Pàgina Principal",
        pacientes: "Pacients",
        gestionUsuarios: "Gestió Usuaris",
        auditoria: "Auditoria",
        configuracion: "Configuració",
        cerrarSesion: "Tancar Sessió",
        seguroCerrarSesion: "Segur que vols tancar sessió?",
        cancelar: "Cancel·lar",
        confirmar: "Confirmar",
        
        // NAVBAR
        sistemaCentralClinico: "Sistema Central Clínic",
        conexionCifrada: "Connexió xifrada d'extrem a extrem",
        avisosDelSistema: "Avisos del Sistema",
        nuevos: "nous",
        noHayNotificaciones: "No hi ha notificacions pendents",
        dr: "Dr.",
        especialista: "Especialista",
        perfilDelUsuario: "Perfil d'Usuari",
        
        // HOMEPAGE
        inicio: "Inici",
        resumenDispositivosPacientes: "Resum de l'estat dels dispositius i pacients en tractament",
        pacientesActivos: "Pacients Actius",
        alertasDeHoy: "Alertes d'avui",
        sincronizacion: "Sincronització",
        pacientesRevisadosRecientemente: "Pacients revisats recentment",
        noHasRevisadoPacientes: "No has revisat pacients recentment.",
        ahoraMismo: "Ara mateix",
        haceMin: "Fa {min}min",
        haceH: "Fa {horas}h",
        
        // PACIENTE PAGE
        gestionDePacientes: "Gestió de pacients",
        gestionDispositivosTratamientos: "Gestió de dispositius i supervisió de tractaments",
        anadirPaciente: "Afegir Pacient",
        buscarPorTarjetaSanitaria: "Cercar per targeta sanitària o nom...",
        estadoTodos: "Estat (Tots)",
        establePositivo: "Estable / Positiu",
        ansiedadDepresion: "Ansietat / Depressió",
        tratamientoTodos: "Tractament (Tots)",
        iodo: "Iode",
        cobalto: "Cobalt",
        paciente: "PACIENT",
        estado: "ESTAT",
        tratamiento: "TRACTAMENT",
        progreso: "PROGRÉS",
        acciones: "ACCIONS",
        cargandoDatosClinicos: "Carregant dades clíniques reals...",
        verPerfil: "Veure Perfil",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "Alta de nou pacient i tractament",
        registroSalutCatalunya: "Registre al fitxer de Salut de Catalunya (CatSalut)",
        datosPersonales: "Dades Personals (CatSalut)",
        nomCognoms: "Nom i Cognoms",
        ejemploNombre: "Ex: Marc García",
        cipTargetaSanitaria: "CIP (Targeta Sanitària)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Data de naixement",
        hospitalReferencia: "Hospital de Referència",
        tractamentRadioisotops: "Tractament de Radioisòtops",
        tipusRadioisotop: "Tipus de Radioisòtop",
        seleccionaIsotopo: "Selecciona un isòtop...",
        iodo131: "Iode-131",
        lutecio177: "Luteci-177",
        cobalto60: "Cobalt-60",
        dosiAdministrada: "Dosi Administrada",
        ejemploDosis: "Ex: 370",
        unitats: "Unitats",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Milicuri (mCi)",
        curis: "Curis (Ci)",
        dataHoraAdministracio: "Data i hora d'administració",
        sincronitzacioDispositius: "Sincronització de Dispositius",
        apropaSmartWatch: "Apropa el SmartWatch compatible del pacient per iniciar la vinculació.",
        buscarDispositiuNFC: "Cercar dispositiu NFC",
        resumAlta: "Resum de l'Alta",
        consentimentInformat: "Consentiment informat registrat.",
        monitoritzacioZeroConfig: "Monitorització Zero-Config activa.",
        calculDecayefectiu: "Càlcul de decaïment segons Te efectiu.",
        confirmarIniciar: "Confirmar i Iniciar",
        porFavorCompletaCampos: "Si us plau, completa tots els camps tècnics.",
        sincronizandoCatsalut: "Sincronitzant amb CatSalut i generant informe...",
        altaCompletada: "Alta completada i informe descarregat amb èxit.",
        errorProcesoAlta: "Error en el procés d'alta",
        aprobaSmartWatch: "Apropa el SmartWatch compatible del pacient per iniciar la vinculació.",
        
        // PERFIL PACIENTE
        patientNoSeleccionado: "Pacient no seleccionat",
        sinTratamiento: "Sense tractament",
        noVinculado: "No vinculat",
        noVinculadoStatus: "No vinculat",
        conectadoTransmitiendo: "Connectat i transmetent",
        tractamentActiu: "Tractament Actiu",
        idPaciente: "ID Pacient",
        dispositivoSmartwatch: "Dispositiu Smartwatch",
        bateria: "Bateria",
        ultimaSinc: "Última sinc",
        sincronizacionRemota: "Sincronització Remota",
        desconectar: "Desconnectar",
        descargaBiometriaAutomatica: "La descàrrega de biometria és automàtica des del dispositiu.",
        progresoRadioterapia: "Progrés Radioteràpia",
        cargaActiva: "Càrrega Activa",
        consonanciaSalud: "Concordança de Salut",
        empujarConsejosReloj: "Envia consells personalitzats a la pantalla del rellotge",
        hidratacionBeberAgua: "Hidratació: Beure 2L d'aigua avui",
        enviadoALas: "Enviat a les",
        seleccionarConsejo: "Seleccionar consell predefinit...",
        evitarContactoNinos: "Evitar contacte amb nens (24h)",
        beberLiquido: "Beure líquid abundant",
        usarBanoExclusivo: "Usar lavabo exclusiu",
        enviarSmartWatch: "Enviar al SmartWatch",
        monitorEmocional: "Monitor Emocional (Evolució setmanal)",
        esteEsEstadoDiario: "Estat diari del pacient (defecte 50%).",
        centroComunicacion: "Centre de comunicació directa",
        consultaGeneral: "Consulta General",
        noHayMensajesNuevos: "No s'han rebut missatges nous avui.",
        mensajeEnviadoExito: "Consell enviat al Smartwatch amb èxit",
        errorEnviarConsejo: "Error en enviar el consell",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "Alta de Nou Personal Mèdic",
        completaDatosRegistrar: "Completa les dades per registrar un nou especialista.",
        datosAcceso: "Dades d'Accés (Usuari)",
        nombreCompleto: "Nom Complet",
        ejemploNombreCompleto: "Ex. Carles Ruiz",
        correoCorporativo: "Correu Electrònic Corporatiu",
        ejemploCorreo: "carles.ruiz@hospital.com",
        contrasenaTemporal: "Contrasenya Temporal",
        asignaContrasena: "Assigna una contrasenya",
        hospitalReferenciaInput: "Hospital de Referència",
        ejemploHospital: "Ex. Hospital Clínic",
        datosProfessionals: "Dades Professionals (Metge)",
        especialidad: "Especialitat",
        seleccionaEspecialidad: "Selecciona una especialitat...",
        oncologiaRadioterapica: "Oncologia Radioteràpica",
        medicinaNuclear: "Medicina Nuclear",
        radiologia: "Radiologia",
        fisicaMedica: "Física Mèdica",
        numeroColegiado: "Número de Col·legiat",
        ejemploColegiado: "Ex. 282893939",
        conectandoServidor: "Connectant amb el servidor de Render...",
        medicoRegistrado: "Metge registrat correctament.",
        errorComunicarServidor: "Error en comunicar amb el servidor.",
        procesar: "Processant...",
        registrarMedicoSistema: "Registrar Metge al Sistema",
        
        // CONFIGURACION
        configuracionSistema: "Configuració del Sistema",
        ajustesCuentaAlertas: "Ajustos de compte, alertes i preferències",
        datosCuenta: "Dades del Compte",
        nombreProfesional: "Nom del Professional",
        correoElectronicoInput: "Correu Electrònic",
        especialidadInput: "Especialitat",
        administracionSistemas: "Administració de Sistemes",
        cambiarContrasena: "Canviar contrasenya",
        preferenciasSistema: "Preferències del Sistema",
        idiomaInterfaz: "Idioma de la interfície",
        zonaHoraria: "Zona Horària",
        europaMadrid: "Europa/Madrid (CET)",
        europaLondres: "Europa/Londres (GMT)",
        notificacionesClinicas: "Notificacions Clíniques",
        bateriaBajaDispositivos: "Bateria baixa en dispositius",
        avisarSmartWatchBaja: "Avisar si baixa del 15%",
        desconexionBiometrica: "Desconnexió biomètrica",
        alertaPerdidaSenal: "Alerta immediata si es perd el senyal",
        resumenSemanal: "Resum setmanal",
        recibirInformeCorreo: "Rebre informe per correu",
        alertaRadiacionSegura: "Alerta de Radiació Segura",
        avisarPacienteNiveles: "Avisar en nivells segurs",
        anomaliaConstantesVitales: "Anomalia en Constants Vitals",
        notificarAlteraciones: "Notificar alteracions cardíaques",
        falloSincronizacion: "Fallada de sincronització",
        avisarRelojNoEnvia: "Avisar si no envia dades (12h)",
        zonaSeguridad: "Zona de Seguretat",
        gestionarSesionesPermisos: "Gestiona sessions i permisos.",
        cerrarSesionTodosTerminales: "Tancar sessió a tots els terminals",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Seguretat del Compte",
        introduceContrasenaActual: "Introdueix la contrasenya actual i la nova.",
        contrasenaActual: "Contrasenya actual",
        nuevaContrasena: "Nova contrasenya",
        confirmarNuevaContrasena: "Confirmar nova contrasenya",
        contrasenasNoCoinciden: "Les contrasenyes noves no coincideixen",
        contrasenaMinimoCaracteres: "Mínim 6 caràcters",
        contrasenaActualizadaExito: "¡Contrasenya actualitzada amb èxit!",
        volverAtras: "Tornar enrere",
        actualizarContrasena: "Actualitzar Contrasenya",
        
        // AUDITORIA
        panelAuditoria: "Panell d'Auditoria",
        controlAccesoSeguridad: "Control d'accés i seguretat",
        facultativo: "FACULTATIU",
        especialidadHeader: "ESPECIALITAT",
        hospital: "HOSPITAL",
        estadoHeader: "ESTAT",
        accionesSeguridad: "ACCIONS SEGURETAT",
        accediendoRegistros: "Accedint a registres...",
        noHayFacultativos: "No hi ha facultatius.",
        seguroCambiarEstado: "¿Canviar estat a {nuevoEstado}?",
        exitoContrasenaActualizada: "Èxit: Contrasenya de {nombre} actualitzada.",
        errorCambiarEstado: "Error en canviar l'estat.",
        asignarNuevaContrasena: "Nova contrasenya per a {nombre}:",
        suspend: "Suspendre",
        activar: "Activar",
        resetPWD: "Reset PWD",
        enviando: "Enviant...",
        
        // ESTADOS
        estable: "Estable",
        activo: "ACTIU",
        inactivo: "INACTIU",
    },

    English: {
        // LOGIN
        bienvenidoAreaPrivada: "Welcome to the Private Area",
        accederCuentaGestion: "Access your management account",
        correoElectronico: "Email address...",
        contrasena: "Password...",
        recordarme: "Remember me",
        quieresCambiarContrasena: "Do you want to change your password?",
        iniciarSesion: "Sign in",
        
        // SIDEBAR
        radioisotopos: "Radioisotopes",
        paginaPrincipal: "Main Page",
        pacientes: "Patients",
        gestionUsuarios: "User Management",
        auditoria: "Audit",
        configuracion: "Settings",
        cerrarSesion: "Sign out",
        seguroCerrarSesion: "Are you sure you want to sign out?",
        cancelar: "Cancel",
        confirmar: "Confirm",
        
        // NAVBAR
        sistemaCentralClinico: "Clinical Central System",
        conexionCifrada: "End-to-end encrypted connection",
        avisosDelSistema: "System Notices",
        nuevos: "new",
        noHayNotificaciones: "No pending notifications",
        dr: "Dr.",
        especialista: "Specialist",
        perfilDelUsuario: "User profile",
        
        // HOMEPAGE
        inicio: "Home",
        resumenDispositivosPacientes: "Summary of device status and patients in treatment",
        pacientesActivos: "Active Patients",
        alertasDeHoy: "Today's Alerts",
        sincronizacion: "Synchronization",
        pacientesRevisadosRecientemente: "Recently reviewed patients",
        noHasRevisadoPacientes: "You haven't reviewed any patients recently.",
        ahoraMismo: "Right now",
        haceMin: "{min}min ago",
        haceH: "{horas}h ago",
        
        // PACIENTE PAGE
        gestionDePacientes: "Patient Management",
        gestionDispositivosTratamientos: "Device management and treatment supervision",
        anadirPaciente: "Add Patient",
        buscarPorTarjetaSanitaria: "Search by health card or name...",
        estadoTodos: "Status (All)",
        establePositivo: "Stable / Positive",
        ansiedadDepresion: "Anxiety / Depression",
        tratamientoTodos: "Treatment (All)",
        iodo: "Iodine",
        cobalto: "Cobalt",
        paciente: "PATIENT",
        estado: "STATUS",
        tratamiento: "TREATMENT",
        progreso: "PROGRESS",
        acciones: "ACTIONS",
        cargandoDatosClinicos: "Loading real clinical data...",
        verPerfil: "View Profile",
        
        // CREAR PACIENTE
        altaPacienteNuevo: "New patient and treatment admission",
        registroSalutCatalunya: "Register to Salut de Catalunya file (CatSalut)",
        datosPersonales: "Personal Data (CatSalut)",
        nomCognoms: "Full Name",
        ejemploNombre: "Ex: John Smith",
        cipTargetaSanitaria: "CIP (Health Card)",
        ejemploCIP: "FARR000000000",
        dataNaixement: "Date of birth",
        hospitalReferencia: "Referral Hospital",
        tractamentRadioisotops: "Radioisotope Treatment",
        tipusRadioisotop: "Radioisotope Type",
        seleccionaIsotopo: "Select an isotope...",
        iodo131: "Iodine-131",
        lutecio177: "Lutetium-177",
        cobalto60: "Cobalt-60",
        dosiAdministrada: "Administered Dose",
        ejemploDosis: "Ex: 370",
        unitats: "Units",
        megaBecquerels: "Mega becquerels (MBq)",
        milicurio: "Millicurie (mCi)",
        curis: "Curies (Ci)",
        dataHoraAdministracio: "Date and time of administration",
        sincronitzacioDispositius: "Device Synchronization",
        apropaSmartWatch: "Bring the patient's compatible SmartWatch close to start pairing.",
        buscarDispositiuNFC: "Search NFC device",
        resumAlta: "Admission Summary",
        consentimentInformat: "Informed consent recorded.",
        monitoritzacioZeroConfig: "Zero-Config monitoring active.",
        calculDecayefectiu: "Decay calculation according to Te effective.",
        confirmarIniciar: "Confirm and Start",
        porFavorCompletaCampos: "Please complete all technical fields.",
        sincronizandoCatsalut: "Synchronizing with CatSalut and generating report...",
        altaCompletada: "Admission completed and report downloaded successfully.",
        errorProcesoAlta: "Error in admission process",
        
        // PERFIL PACIENTE
        patientNoSeleccionado: "No patient selected",
        sinTratamiento: "No treatment",
        noVinculado: "Not linked",
        noVinculadoStatus: "Not linked",
        conectadoTransmitiendo: "Connected and transmitting",
        tractamentActiu: "Active Treatment",
        idPaciente: "Patient ID",
        dispositivoSmartwatch: "Smartwatch Device",
        bateria: "Battery",
        ultimaSinc: "Last sync",
        sincronizacionRemota: "Remote Synchronization",
        desconectar: "Disconnect",
        descargaBiometriaAutomatica: "Biometrics download is automatic from the patient's device.",
        progresoRadioterapia: "Radiotherapy Progress",
        cargaActiva: "Active Dose",
        consonanciaSalud: "Health Harmony",
        empujarConsejosReloj: "Push personalized advice to the watch screen",
        hidratacionBeberAgua: "Hydration: Drink 2L of water today",
        enviadoALas: "Sent at",
        seleccionarConsejo: "Select predefined advice...",
        evitarContactoNinos: "Avoid contact with children (24h)",
        beberLiquido: "Drink plenty of liquid",
        usarBanoExclusivo: "Use exclusive bathroom",
        enviarSmartWatch: "Send to SmartWatch",
        monitorEmocional: "Emotional Monitor (Weekly evolution)",
        esteEsEstadoDiario: "Patient's daily status (default 50%).",
        centroComunicacion: "Direct communication center",
        consultaGeneral: "General Inquiry",
        noHayMensajesNuevos: "No new messages received today.",
        mensajeEnviadoExito: "Advice sent to Smartwatch successfully",
        errorEnviarConsejo: "Error sending advice",
        
        // GESTION USUARIO
        altaNuevoPersonalMedico: "New Medical Staff Registration",
        completaDatosRegistrar: "Complete the data to register a new specialist.",
        datosAcceso: "Access Data (User)",
        nombreCompleto: "Full Name",
        ejemploNombreCompleto: "Ex. John Doe",
        correoCorporativo: "Corporate Email",
        ejemploCorreo: "john.doe@hospital.com",
        contrasenaTemporal: "Temporary Password",
        asignaContrasena: "Assign a password",
        hospitalReferenciaInput: "Referral Hospital",
        ejemploHospital: "Ex. General Hospital",
        datosProfesionales: "Professional Data (Physician)",
        especialidad: "Specialty",
        seleccionaEspecialidad: "Select a specialty...",
        oncologiaRadioterapica: "Radiation Oncology",
        medicinaNuclear: "Nuclear Medicine",
        radiologia: "Radiology",
        fisicaMedica: "Medical Physics",
        numeroColegiado: "License Number",
        ejemploColegiado: "Ex. 282893939",
        conectandoServidor: "Connecting to Render server...",
        medicoRegistrado: "Physician registered successfully.",
        errorComunicarServidor: "Error communicating with the server.",
        procesar: "Processing...",
        registrarMedicoSistema: "Register Physician in System",
        
        // CONFIGURACION
        configuracionSistema: "System Settings",
        ajustesCuentaAlertas: "Account settings, alerts and clinical preferences",
        datosCuenta: "Account Data",
        nombreProfesional: "Professional Name",
        correoElectronicoInput: "Email Address",
        especialidadInput: "Specialty",
        administracionSistemas: "System Administration",
        cambiarContrasena: "Change password",
        preferenciasSistema: "System Preferences",
        idiomaInterfaz: "Interface Language",
        zonaHoraria: "Time Zone",
        europaMadrid: "Europe/Madrid (CET)",
        europaLondres: "Europe/London (GMT)",
        notificacionesClinicas: "Clinical Notifications",
        bateriaBajaDispositivos: "Low battery on devices",
        avisarSmartWatchBaja: "Alert if drops below 15%",
        desconexionBiometrica: "Biometric disconnection",
        alertaPerdidaSenal: "Immediate alert if signal is lost",
        resumenSemanal: "Weekly summary",
        recibirInformeCorreo: "Receive report by email",
        alertaRadiacionSegura: "Safe Radiation Alert",
        avisarPacienteNiveles: "Alert at safe levels",
        anomaliaConstantesVitales: "Vital Signs Anomaly",
        notificarAlteraciones: "Notify cardiac alterations",
        falloSincronizacion: "Synchronization failure",
        avisarRelojNoEnvia: "Alert if watch doesn't send data (12h)",
        zonaSeguridad: "Security Zone",
        gestionarSesionesPermisos: "Manage sessions and permissions.",
        cerrarSesionTodosTerminales: "Sign out from all terminals",
        
        // CAMBIAR PASSWORD
        seguridadCuenta: "Account Security",
        introduceContrasenaActual: "Enter your current and new password.",
        contrasenaActual: "Current password",
        nuevaContrasena: "New password",
        confirmarNuevaContrasena: "Confirm new password",
        contrasenasNoCoinciden: "New passwords don't match",
        contrasenaMinimoCaracteres: "Minimum 6 characters",
        contrasenaActualizadaExito: "Password updated!",
        volverAtras: "Go back",
        actualizarContrasena: "Update Password",
        
        // AUDITORIA
        panelAuditoria: "Audit Panel",
        controlAccesoSeguridad: "Access control and security",
        facultativo: "PHYSICIAN",
        especialidadHeader: "SPECIALTY",
        hospital: "HOSPITAL",
        estadoHeader: "STATUS",
        accionesSeguridad: "SECURITY ACTIONS",
        accediendoRegistros: "Accessing security records...",
        noHayFacultativos: "No registered physicians.",
        seguroCambiarEstado: "Change status to {nuevoEstado}?",
        exitoContrasenaActualizada: "Success: Password for {nombre} updated.",
        errorCambiarEstado: "Error changing status.",
        asignarNuevaContrasena: "New temporary password for {nombre}:",
        suspend: "Suspend",
        activar: "Activate",
        resetPWD: "Reset PWD",
        enviando: "Sending...",
        
        // ESTADOS
        estable: "Stable",
        activo: "ACTIVE",
        inactivo: "INACTIVE",
    }
};